// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: relayv1/relay.proto

package relayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED    TaskStatus = 0
	TaskStatus_TASK_STATUS_RUNNING        TaskStatus = 1
	TaskStatus_TASK_STATUS_DONE           TaskStatus = 2
	TaskStatus_TASK_STATUS_FAILED         TaskStatus = 3
	TaskStatus_TASK_STATUS_TIMED_OUT      TaskStatus = 4
	TaskStatus_TASK_STATUS_PREPARING      TaskStatus = 5
	TaskStatus_TASK_STATUS_PREPARE_FAILED TaskStatus = 6
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_RUNNING",
		2: "TASK_STATUS_DONE",
		3: "TASK_STATUS_FAILED",
		4: "TASK_STATUS_TIMED_OUT",
		5: "TASK_STATUS_PREPARING",
		6: "TASK_STATUS_PREPARE_FAILED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED":    0,
		"TASK_STATUS_RUNNING":        1,
		"TASK_STATUS_DONE":           2,
		"TASK_STATUS_FAILED":         3,
		"TASK_STATUS_TIMED_OUT":      4,
		"TASK_STATUS_PREPARING":      5,
		"TASK_STATUS_PREPARE_FAILED": 6,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_relayv1_relay_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_relayv1_relay_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{0}
}

type LogStream int32

const (
	LogStream_LOG_STREAM_UNSPECIFIED LogStream = 0
	LogStream_LOG_STREAM_STDOUT      LogStream = 1
	LogStream_LOG_STREAM_STDERR      LogStream = 2
	LogStream_LOG_STREAM_PREPARE     LogStream = 3
)

// Enum value maps for LogStream.
var (
	LogStream_name = map[int32]string{
		0: "LOG_STREAM_UNSPECIFIED",
		1: "LOG_STREAM_STDOUT",
		2: "LOG_STREAM_STDERR",
		3: "LOG_STREAM_PREPARE",
	}
	LogStream_value = map[string]int32{
		"LOG_STREAM_UNSPECIFIED": 0,
		"LOG_STREAM_STDOUT":      1,
		"LOG_STREAM_STDERR":      2,
		"LOG_STREAM_PREPARE":     3,
	}
)

func (x LogStream) Enum() *LogStream {
	p := new(LogStream)
	*p = x
	return p
}

func (x LogStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStream) Descriptor() protoreflect.EnumDescriptor {
	return file_relayv1_relay_proto_enumTypes[1].Descriptor()
}

func (LogStream) Type() protoreflect.EnumType {
	return &file_relayv1_relay_proto_enumTypes[1]
}

func (x LogStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStream.Descriptor instead.
func (LogStream) EnumDescriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{1}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_TaskStatus
	//	*AgentMessage_TaskLog
	//	*AgentMessage_WorkspaceInventory
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_relayv1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskStatus() *TaskStatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TaskStatus); ok {
			return x.TaskStatus
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskLog() *TaskLogChunk {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TaskLog); ok {
			return x.TaskLog
		}
	}
	return nil
}

func (x *AgentMessage) GetWorkspaceInventory() *WorkspaceInventoryUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_WorkspaceInventory); ok {
			return x.WorkspaceInventory
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_TaskStatus struct {
	TaskStatus *TaskStatusUpdate `protobuf:"bytes,2,opt,name=task_status,json=taskStatus,proto3,oneof"`
}

type AgentMessage_TaskLog struct {
	TaskLog *TaskLogChunk `protobuf:"bytes,3,opt,name=task_log,json=taskLog,proto3,oneof"`
}

type AgentMessage_WorkspaceInventory struct {
	WorkspaceInventory *WorkspaceInventoryUpdate `protobuf:"bytes,4,opt,name=workspace_inventory,json=workspaceInventory,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_TaskStatus) isAgentMessage_Payload() {}

func (*AgentMessage_TaskLog) isAgentMessage_Payload() {}

func (*AgentMessage_WorkspaceInventory) isAgentMessage_Payload() {}

// Sent once when the stream opens. worker_id is empty on first registration.
// running_tasks is the agent's list of currently-executing tasks at reconnect
// time (empty on first connect). The coordinator diffs against DB state and
// replies with RegisterResponse.cancel_task_ids for any stale assignments.
//
// Exactly one credential field must be set. enrollment_token is used only on
// first boot of a fresh agent; every subsequent reconnect sends agent_token.
type RegisterRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	WorkerId     string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Hostname     string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CpuCores     int32                  `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	RamGb        int32                  `protobuf:"varint,4,opt,name=ram_gb,json=ramGb,proto3" json:"ram_gb,omitempty"`
	GpuCount     int32                  `protobuf:"varint,5,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	GpuModel     string                 `protobuf:"bytes,6,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`
	Os           string                 `protobuf:"bytes,7,opt,name=os,proto3" json:"os,omitempty"`
	RunningTasks []*RunningTask         `protobuf:"bytes,8,rep,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	// Types that are valid to be assigned to Credential:
	//
	//	*RegisterRequest_EnrollmentToken
	//	*RegisterRequest_AgentToken
	Credential    isRegisterRequest_Credential `protobuf_oneof:"credential"`
	Inventory     []*WorkspaceInventoryUpdate  `protobuf:"bytes,11,rep,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_relayv1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *RegisterRequest) GetRamGb() int32 {
	if x != nil {
		return x.RamGb
	}
	return 0
}

func (x *RegisterRequest) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *RegisterRequest) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetRunningTasks() []*RunningTask {
	if x != nil {
		return x.RunningTasks
	}
	return nil
}

func (x *RegisterRequest) GetCredential() isRegisterRequest_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *RegisterRequest) GetEnrollmentToken() string {
	if x != nil {
		if x, ok := x.Credential.(*RegisterRequest_EnrollmentToken); ok {
			return x.EnrollmentToken
		}
	}
	return ""
}

func (x *RegisterRequest) GetAgentToken() string {
	if x != nil {
		if x, ok := x.Credential.(*RegisterRequest_AgentToken); ok {
			return x.AgentToken
		}
	}
	return ""
}

func (x *RegisterRequest) GetInventory() []*WorkspaceInventoryUpdate {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type isRegisterRequest_Credential interface {
	isRegisterRequest_Credential()
}

type RegisterRequest_EnrollmentToken struct {
	EnrollmentToken string `protobuf:"bytes,9,opt,name=enrollment_token,json=enrollmentToken,proto3,oneof"`
}

type RegisterRequest_AgentToken struct {
	AgentToken string `protobuf:"bytes,10,opt,name=agent_token,json=agentToken,proto3,oneof"`
}

func (*RegisterRequest_EnrollmentToken) isRegisterRequest_Credential() {}

func (*RegisterRequest_AgentToken) isRegisterRequest_Credential() {}

// A task the agent believes it is currently running, with the epoch assigned
// at dispatch time. The coordinator uses this to detect stale assignments.
type RunningTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningTask) Reset() {
	*x = RunningTask{}
	mi := &file_relayv1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningTask) ProtoMessage() {}

func (x *RunningTask) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningTask.ProtoReflect.Descriptor instead.
func (*RunningTask) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *RunningTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RunningTask) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type TaskStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=relay.v1.TaskStatus" json:"status,omitempty"`
	ExitCode      *int32                 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Epoch         int64                  `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusUpdate) Reset() {
	*x = TaskStatusUpdate{}
	mi := &file_relayv1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdate) ProtoMessage() {}

func (x *TaskStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdate.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdate) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *TaskStatusUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusUpdate) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskStatusUpdate) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *TaskStatusUpdate) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskStatusUpdate) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type TaskLogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Stream        LogStream              `protobuf:"varint,2,opt,name=stream,proto3,enum=relay.v1.LogStream" json:"stream,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Epoch         int64                  `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogChunk) Reset() {
	*x = TaskLogChunk{}
	mi := &file_relayv1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogChunk) ProtoMessage() {}

func (x *TaskLogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogChunk.ProtoReflect.Descriptor instead.
func (*TaskLogChunk) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *TaskLogChunk) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskLogChunk) GetStream() LogStream {
	if x != nil {
		return x.Stream
	}
	return LogStream_LOG_STREAM_UNSPECIFIED
}

func (x *TaskLogChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *TaskLogChunk) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type CoordinatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CoordinatorMessage_RegisterResponse
	//	*CoordinatorMessage_DispatchTask
	//	*CoordinatorMessage_CancelTask
	//	*CoordinatorMessage_EvictWorkspace
	Payload       isCoordinatorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_relayv1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{5}
}

func (x *CoordinatorMessage) GetPayload() isCoordinatorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CoordinatorMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetDispatchTask() *DispatchTask {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_DispatchTask); ok {
			return x.DispatchTask
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetCancelTask() *CancelTask {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_CancelTask); ok {
			return x.CancelTask
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetEvictWorkspace() *EvictWorkspaceCommand {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_EvictWorkspace); ok {
			return x.EvictWorkspace
		}
	}
	return nil
}

type isCoordinatorMessage_Payload interface {
	isCoordinatorMessage_Payload()
}

type CoordinatorMessage_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,1,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type CoordinatorMessage_DispatchTask struct {
	DispatchTask *DispatchTask `protobuf:"bytes,2,opt,name=dispatch_task,json=dispatchTask,proto3,oneof"`
}

type CoordinatorMessage_CancelTask struct {
	CancelTask *CancelTask `protobuf:"bytes,3,opt,name=cancel_task,json=cancelTask,proto3,oneof"`
}

type CoordinatorMessage_EvictWorkspace struct {
	EvictWorkspace *EvictWorkspaceCommand `protobuf:"bytes,4,opt,name=evict_workspace,json=evictWorkspace,proto3,oneof"`
}

func (*CoordinatorMessage_RegisterResponse) isCoordinatorMessage_Payload() {}

func (*CoordinatorMessage_DispatchTask) isCoordinatorMessage_Payload() {}

func (*CoordinatorMessage_CancelTask) isCoordinatorMessage_Payload() {}

func (*CoordinatorMessage_EvictWorkspace) isCoordinatorMessage_Payload() {}

// Sent in response to RegisterRequest. agent_token is populated only on
// successful enrollment (first connect with a valid enrollment_token); the
// agent must persist it and send it as agent_token on every reconnect.
// cancel_task_ids lists tasks the agent reported as running that the
// coordinator considers stale.
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CancelTaskIds []string               `protobuf:"bytes,2,rep,name=cancel_task_ids,json=cancelTaskIds,proto3" json:"cancel_task_ids,omitempty"`
	AgentToken    string                 `protobuf:"bytes,3,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_relayv1_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterResponse) GetCancelTaskIds() []string {
	if x != nil {
		return x.CancelTaskIds
	}
	return nil
}

func (x *RegisterResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

type DispatchTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId          string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Epoch          int64                  `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Source         *SourceSpec            `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Commands       []*CommandLine         `protobuf:"bytes,8,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispatchTask) Reset() {
	*x = DispatchTask{}
	mi := &file_relayv1_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTask) ProtoMessage() {}

func (x *DispatchTask) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTask.ProtoReflect.Descriptor instead.
func (*DispatchTask) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{7}
}

func (x *DispatchTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DispatchTask) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DispatchTask) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *DispatchTask) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *DispatchTask) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *DispatchTask) GetSource() *SourceSpec {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *DispatchTask) GetCommands() []*CommandLine {
	if x != nil {
		return x.Commands
	}
	return nil
}

// CommandLine carries a single argv (executable + args). A task runs each
// CommandLine in `DispatchTask.commands` sequentially in the same workspace
// and environment; first non-zero exit fails the task.
type CommandLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Argv          []string               `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandLine) Reset() {
	*x = CommandLine{}
	mi := &file_relayv1_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandLine) ProtoMessage() {}

func (x *CommandLine) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandLine.ProtoReflect.Descriptor instead.
func (*CommandLine) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{8}
}

func (x *CommandLine) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

type CancelTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTask) Reset() {
	*x = CancelTask{}
	mi := &file_relayv1_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTask) ProtoMessage() {}

func (x *CancelTask) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTask.ProtoReflect.Descriptor instead.
func (*CancelTask) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{9}
}

func (x *CancelTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type SourceSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Provider:
	//
	//	*SourceSpec_Perforce
	Provider      isSourceSpec_Provider `protobuf_oneof:"provider"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceSpec) Reset() {
	*x = SourceSpec{}
	mi := &file_relayv1_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceSpec) ProtoMessage() {}

func (x *SourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceSpec.ProtoReflect.Descriptor instead.
func (*SourceSpec) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{10}
}

func (x *SourceSpec) GetProvider() isSourceSpec_Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *SourceSpec) GetPerforce() *PerforceSource {
	if x != nil {
		if x, ok := x.Provider.(*SourceSpec_Perforce); ok {
			return x.Perforce
		}
	}
	return nil
}

type isSourceSpec_Provider interface {
	isSourceSpec_Provider()
}

type SourceSpec_Perforce struct {
	Perforce *PerforceSource `protobuf:"bytes,1,opt,name=perforce,proto3,oneof"`
}

func (*SourceSpec_Perforce) isSourceSpec_Provider() {}

type PerforceSource struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Stream             string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Sync               []*SyncEntry           `protobuf:"bytes,2,rep,name=sync,proto3" json:"sync,omitempty"`
	Unshelves          []int64                `protobuf:"varint,3,rep,packed,name=unshelves,proto3" json:"unshelves,omitempty"`
	WorkspaceExclusive bool                   `protobuf:"varint,4,opt,name=workspace_exclusive,json=workspaceExclusive,proto3" json:"workspace_exclusive,omitempty"`
	ClientTemplate     *string                `protobuf:"bytes,5,opt,name=client_template,json=clientTemplate,proto3,oneof" json:"client_template,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PerforceSource) Reset() {
	*x = PerforceSource{}
	mi := &file_relayv1_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerforceSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerforceSource) ProtoMessage() {}

func (x *PerforceSource) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerforceSource.ProtoReflect.Descriptor instead.
func (*PerforceSource) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{11}
}

func (x *PerforceSource) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *PerforceSource) GetSync() []*SyncEntry {
	if x != nil {
		return x.Sync
	}
	return nil
}

func (x *PerforceSource) GetUnshelves() []int64 {
	if x != nil {
		return x.Unshelves
	}
	return nil
}

func (x *PerforceSource) GetWorkspaceExclusive() bool {
	if x != nil {
		return x.WorkspaceExclusive
	}
	return false
}

func (x *PerforceSource) GetClientTemplate() string {
	if x != nil && x.ClientTemplate != nil {
		return *x.ClientTemplate
	}
	return ""
}

type SyncEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Rev           string                 `protobuf:"bytes,2,opt,name=rev,proto3" json:"rev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEntry) Reset() {
	*x = SyncEntry{}
	mi := &file_relayv1_relay_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEntry) ProtoMessage() {}

func (x *SyncEntry) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEntry.ProtoReflect.Descriptor instead.
func (*SyncEntry) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{12}
}

func (x *SyncEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SyncEntry) GetRev() string {
	if x != nil {
		return x.Rev
	}
	return ""
}

type WorkspaceInventoryUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceType    string                 `protobuf:"bytes,1,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceKey     string                 `protobuf:"bytes,2,opt,name=source_key,json=sourceKey,proto3" json:"source_key,omitempty"`
	ShortId       string                 `protobuf:"bytes,3,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	BaselineHash  string                 `protobuf:"bytes,4,opt,name=baseline_hash,json=baselineHash,proto3" json:"baseline_hash,omitempty"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	LastUsedAt    string                 `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceInventoryUpdate) Reset() {
	*x = WorkspaceInventoryUpdate{}
	mi := &file_relayv1_relay_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceInventoryUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceInventoryUpdate) ProtoMessage() {}

func (x *WorkspaceInventoryUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceInventoryUpdate.ProtoReflect.Descriptor instead.
func (*WorkspaceInventoryUpdate) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{13}
}

func (x *WorkspaceInventoryUpdate) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *WorkspaceInventoryUpdate) GetSourceKey() string {
	if x != nil {
		return x.SourceKey
	}
	return ""
}

func (x *WorkspaceInventoryUpdate) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

func (x *WorkspaceInventoryUpdate) GetBaselineHash() string {
	if x != nil {
		return x.BaselineHash
	}
	return ""
}

func (x *WorkspaceInventoryUpdate) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *WorkspaceInventoryUpdate) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

type EvictWorkspaceCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceType    string                 `protobuf:"bytes,1,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	ShortId       string                 `protobuf:"bytes,2,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictWorkspaceCommand) Reset() {
	*x = EvictWorkspaceCommand{}
	mi := &file_relayv1_relay_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictWorkspaceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictWorkspaceCommand) ProtoMessage() {}

func (x *EvictWorkspaceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictWorkspaceCommand.ProtoReflect.Descriptor instead.
func (*EvictWorkspaceCommand) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{14}
}

func (x *EvictWorkspaceCommand) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *EvictWorkspaceCommand) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

var File_relayv1_relay_proto protoreflect.FileDescriptor

const file_relayv1_relay_proto_rawDesc = "" +
	"\n" +
	"\x13relayv1/relay.proto\x12\brelay.v1\"\x9d\x02\n" +
	"\fAgentMessage\x127\n" +
	"\bregister\x18\x01 \x01(\v2\x19.relay.v1.RegisterRequestH\x00R\bregister\x12=\n" +
	"\vtask_status\x18\x02 \x01(\v2\x1a.relay.v1.TaskStatusUpdateH\x00R\n" +
	"taskStatus\x123\n" +
	"\btask_log\x18\x03 \x01(\v2\x16.relay.v1.TaskLogChunkH\x00R\ataskLog\x12U\n" +
	"\x13workspace_inventory\x18\x04 \x01(\v2\".relay.v1.WorkspaceInventoryUpdateH\x00R\x12workspaceInventoryB\t\n" +
	"\apayload\"\xa4\x03\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\x05R\bcpuCores\x12\x15\n" +
	"\x06ram_gb\x18\x04 \x01(\x05R\x05ramGb\x12\x1b\n" +
	"\tgpu_count\x18\x05 \x01(\x05R\bgpuCount\x12\x1b\n" +
	"\tgpu_model\x18\x06 \x01(\tR\bgpuModel\x12\x0e\n" +
	"\x02os\x18\a \x01(\tR\x02os\x12:\n" +
	"\rrunning_tasks\x18\b \x03(\v2\x15.relay.v1.RunningTaskR\frunningTasks\x12+\n" +
	"\x10enrollment_token\x18\t \x01(\tH\x00R\x0fenrollmentToken\x12!\n" +
	"\vagent_token\x18\n" +
	" \x01(\tH\x00R\n" +
	"agentToken\x12@\n" +
	"\tinventory\x18\v \x03(\v2\".relay.v1.WorkspaceInventoryUpdateR\tinventoryB\f\n" +
	"\n" +
	"credential\"<\n" +
	"\vRunningTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\"\xc4\x01\n" +
	"\x10TaskStatusUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.relay.v1.TaskStatusR\x06status\x12 \n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCode\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x03R\x05epochB\f\n" +
	"\n" +
	"_exit_code\"\x84\x01\n" +
	"\fTaskLogChunk\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12+\n" +
	"\x06stream\x18\x02 \x01(\x0e2\x13.relay.v1.LogStreamR\x06stream\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x03R\x05epoch\"\xae\x02\n" +
	"\x12CoordinatorMessage\x12I\n" +
	"\x11register_response\x18\x01 \x01(\v2\x1a.relay.v1.RegisterResponseH\x00R\x10registerResponse\x12=\n" +
	"\rdispatch_task\x18\x02 \x01(\v2\x16.relay.v1.DispatchTaskH\x00R\fdispatchTask\x127\n" +
	"\vcancel_task\x18\x03 \x01(\v2\x14.relay.v1.CancelTaskH\x00R\n" +
	"cancelTask\x12J\n" +
	"\x0fevict_workspace\x18\x04 \x01(\v2\x1f.relay.v1.EvictWorkspaceCommandH\x00R\x0eevictWorkspaceB\t\n" +
	"\apayload\"x\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12&\n" +
	"\x0fcancel_task_ids\x18\x02 \x03(\tR\rcancelTaskIds\x12\x1f\n" +
	"\vagent_token\x18\x03 \x01(\tR\n" +
	"agentToken\"\xd8\x02\n" +
	"\fDispatchTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x121\n" +
	"\x03env\x18\x04 \x03(\v2\x1f.relay.v1.DispatchTask.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x14\n" +
	"\x05epoch\x18\x06 \x01(\x03R\x05epoch\x12,\n" +
	"\x06source\x18\a \x01(\v2\x14.relay.v1.SourceSpecR\x06source\x121\n" +
	"\bcommands\x18\b \x03(\v2\x15.relay.v1.CommandLineR\bcommands\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x03\x10\x04R\acommand\"!\n" +
	"\vCommandLine\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\"%\n" +
	"\n" +
	"CancelTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"P\n" +
	"\n" +
	"SourceSpec\x126\n" +
	"\bperforce\x18\x01 \x01(\v2\x18.relay.v1.PerforceSourceH\x00R\bperforceB\n" +
	"\n" +
	"\bprovider\"\xe2\x01\n" +
	"\x0ePerforceSource\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12'\n" +
	"\x04sync\x18\x02 \x03(\v2\x13.relay.v1.SyncEntryR\x04sync\x12\x1c\n" +
	"\tunshelves\x18\x03 \x03(\x03R\tunshelves\x12/\n" +
	"\x13workspace_exclusive\x18\x04 \x01(\bR\x12workspaceExclusive\x12,\n" +
	"\x0fclient_template\x18\x05 \x01(\tH\x00R\x0eclientTemplate\x88\x01\x01B\x12\n" +
	"\x10_client_template\"1\n" +
	"\tSyncEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x10\n" +
	"\x03rev\x18\x02 \x01(\tR\x03rev\"\xd6\x01\n" +
	"\x18WorkspaceInventoryUpdate\x12\x1f\n" +
	"\vsource_type\x18\x01 \x01(\tR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"source_key\x18\x02 \x01(\tR\tsourceKey\x12\x19\n" +
	"\bshort_id\x18\x03 \x01(\tR\ashortId\x12#\n" +
	"\rbaseline_hash\x18\x04 \x01(\tR\fbaselineHash\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\x12 \n" +
	"\flast_used_at\x18\x06 \x01(\tR\n" +
	"lastUsedAt\"S\n" +
	"\x15EvictWorkspaceCommand\x12\x1f\n" +
	"\vsource_type\x18\x01 \x01(\tR\n" +
	"sourceType\x12\x19\n" +
	"\bshort_id\x18\x02 \x01(\tR\ashortId*\xc6\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x01\x12\x14\n" +
	"\x10TASK_STATUS_DONE\x10\x02\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_TIMED_OUT\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_PREPARING\x10\x05\x12\x1e\n" +
	"\x1aTASK_STATUS_PREPARE_FAILED\x10\x06*m\n" +
	"\tLogStream\x12\x1a\n" +
	"\x16LOG_STREAM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOG_STREAM_STDOUT\x10\x01\x12\x15\n" +
	"\x11LOG_STREAM_STDERR\x10\x02\x12\x16\n" +
	"\x12LOG_STREAM_PREPARE\x10\x032S\n" +
	"\fAgentService\x12C\n" +
	"\aConnect\x12\x16.relay.v1.AgentMessage\x1a\x1c.relay.v1.CoordinatorMessage(\x010\x01B\x1eZ\x1crelay/internal/proto/relayv1b\x06proto3"

var (
	file_relayv1_relay_proto_rawDescOnce sync.Once
	file_relayv1_relay_proto_rawDescData []byte
)

func file_relayv1_relay_proto_rawDescGZIP() []byte {
	file_relayv1_relay_proto_rawDescOnce.Do(func() {
		file_relayv1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relayv1_relay_proto_rawDesc), len(file_relayv1_relay_proto_rawDesc)))
	})
	return file_relayv1_relay_proto_rawDescData
}

var file_relayv1_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_relayv1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_relayv1_relay_proto_goTypes = []any{
	(TaskStatus)(0),                  // 0: relay.v1.TaskStatus
	(LogStream)(0),                   // 1: relay.v1.LogStream
	(*AgentMessage)(nil),             // 2: relay.v1.AgentMessage
	(*RegisterRequest)(nil),          // 3: relay.v1.RegisterRequest
	(*RunningTask)(nil),              // 4: relay.v1.RunningTask
	(*TaskStatusUpdate)(nil),         // 5: relay.v1.TaskStatusUpdate
	(*TaskLogChunk)(nil),             // 6: relay.v1.TaskLogChunk
	(*CoordinatorMessage)(nil),       // 7: relay.v1.CoordinatorMessage
	(*RegisterResponse)(nil),         // 8: relay.v1.RegisterResponse
	(*DispatchTask)(nil),             // 9: relay.v1.DispatchTask
	(*CommandLine)(nil),              // 10: relay.v1.CommandLine
	(*CancelTask)(nil),               // 11: relay.v1.CancelTask
	(*SourceSpec)(nil),               // 12: relay.v1.SourceSpec
	(*PerforceSource)(nil),           // 13: relay.v1.PerforceSource
	(*SyncEntry)(nil),                // 14: relay.v1.SyncEntry
	(*WorkspaceInventoryUpdate)(nil), // 15: relay.v1.WorkspaceInventoryUpdate
	(*EvictWorkspaceCommand)(nil),    // 16: relay.v1.EvictWorkspaceCommand
	nil,                              // 17: relay.v1.DispatchTask.EnvEntry
}
var file_relayv1_relay_proto_depIdxs = []int32{
	3,  // 0: relay.v1.AgentMessage.register:type_name -> relay.v1.RegisterRequest
	5,  // 1: relay.v1.AgentMessage.task_status:type_name -> relay.v1.TaskStatusUpdate
	6,  // 2: relay.v1.AgentMessage.task_log:type_name -> relay.v1.TaskLogChunk
	15, // 3: relay.v1.AgentMessage.workspace_inventory:type_name -> relay.v1.WorkspaceInventoryUpdate
	4,  // 4: relay.v1.RegisterRequest.running_tasks:type_name -> relay.v1.RunningTask
	15, // 5: relay.v1.RegisterRequest.inventory:type_name -> relay.v1.WorkspaceInventoryUpdate
	0,  // 6: relay.v1.TaskStatusUpdate.status:type_name -> relay.v1.TaskStatus
	1,  // 7: relay.v1.TaskLogChunk.stream:type_name -> relay.v1.LogStream
	8,  // 8: relay.v1.CoordinatorMessage.register_response:type_name -> relay.v1.RegisterResponse
	9,  // 9: relay.v1.CoordinatorMessage.dispatch_task:type_name -> relay.v1.DispatchTask
	11, // 10: relay.v1.CoordinatorMessage.cancel_task:type_name -> relay.v1.CancelTask
	16, // 11: relay.v1.CoordinatorMessage.evict_workspace:type_name -> relay.v1.EvictWorkspaceCommand
	17, // 12: relay.v1.DispatchTask.env:type_name -> relay.v1.DispatchTask.EnvEntry
	12, // 13: relay.v1.DispatchTask.source:type_name -> relay.v1.SourceSpec
	10, // 14: relay.v1.DispatchTask.commands:type_name -> relay.v1.CommandLine
	13, // 15: relay.v1.SourceSpec.perforce:type_name -> relay.v1.PerforceSource
	14, // 16: relay.v1.PerforceSource.sync:type_name -> relay.v1.SyncEntry
	2,  // 17: relay.v1.AgentService.Connect:input_type -> relay.v1.AgentMessage
	7,  // 18: relay.v1.AgentService.Connect:output_type -> relay.v1.CoordinatorMessage
	18, // [18:19] is the sub-list for method output_type
	17, // [17:18] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_relayv1_relay_proto_init() }
func file_relayv1_relay_proto_init() {
	if File_relayv1_relay_proto != nil {
		return
	}
	file_relayv1_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_TaskStatus)(nil),
		(*AgentMessage_TaskLog)(nil),
		(*AgentMessage_WorkspaceInventory)(nil),
	}
	file_relayv1_relay_proto_msgTypes[1].OneofWrappers = []any{
		(*RegisterRequest_EnrollmentToken)(nil),
		(*RegisterRequest_AgentToken)(nil),
	}
	file_relayv1_relay_proto_msgTypes[3].OneofWrappers = []any{}
	file_relayv1_relay_proto_msgTypes[5].OneofWrappers = []any{
		(*CoordinatorMessage_RegisterResponse)(nil),
		(*CoordinatorMessage_DispatchTask)(nil),
		(*CoordinatorMessage_CancelTask)(nil),
		(*CoordinatorMessage_EvictWorkspace)(nil),
	}
	file_relayv1_relay_proto_msgTypes[10].OneofWrappers = []any{
		(*SourceSpec_Perforce)(nil),
	}
	file_relayv1_relay_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relayv1_relay_proto_rawDesc), len(file_relayv1_relay_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relayv1_relay_proto_goTypes,
		DependencyIndexes: file_relayv1_relay_proto_depIdxs,
		EnumInfos:         file_relayv1_relay_proto_enumTypes,
		MessageInfos:      file_relayv1_relay_proto_msgTypes,
	}.Build()
	File_relayv1_relay_proto = out.File
	file_relayv1_relay_proto_goTypes = nil
	file_relayv1_relay_proto_depIdxs = nil
}
