// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: relayv1/relay.proto

package relayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 1
	TaskStatus_TASK_STATUS_DONE        TaskStatus = 2
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 3
	TaskStatus_TASK_STATUS_TIMED_OUT   TaskStatus = 4
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_RUNNING",
		2: "TASK_STATUS_DONE",
		3: "TASK_STATUS_FAILED",
		4: "TASK_STATUS_TIMED_OUT",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_RUNNING":     1,
		"TASK_STATUS_DONE":        2,
		"TASK_STATUS_FAILED":      3,
		"TASK_STATUS_TIMED_OUT":   4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_relayv1_relay_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_relayv1_relay_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{0}
}

type LogStream int32

const (
	LogStream_LOG_STREAM_UNSPECIFIED LogStream = 0
	LogStream_LOG_STREAM_STDOUT      LogStream = 1
	LogStream_LOG_STREAM_STDERR      LogStream = 2
)

// Enum value maps for LogStream.
var (
	LogStream_name = map[int32]string{
		0: "LOG_STREAM_UNSPECIFIED",
		1: "LOG_STREAM_STDOUT",
		2: "LOG_STREAM_STDERR",
	}
	LogStream_value = map[string]int32{
		"LOG_STREAM_UNSPECIFIED": 0,
		"LOG_STREAM_STDOUT":      1,
		"LOG_STREAM_STDERR":      2,
	}
)

func (x LogStream) Enum() *LogStream {
	p := new(LogStream)
	*p = x
	return p
}

func (x LogStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStream) Descriptor() protoreflect.EnumDescriptor {
	return file_relayv1_relay_proto_enumTypes[1].Descriptor()
}

func (LogStream) Type() protoreflect.EnumType {
	return &file_relayv1_relay_proto_enumTypes[1]
}

func (x LogStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStream.Descriptor instead.
func (LogStream) EnumDescriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{1}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_TaskStatus
	//	*AgentMessage_TaskLog
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_relayv1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskStatus() *TaskStatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TaskStatus); ok {
			return x.TaskStatus
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskLog() *TaskLogChunk {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TaskLog); ok {
			return x.TaskLog
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_TaskStatus struct {
	TaskStatus *TaskStatusUpdate `protobuf:"bytes,2,opt,name=task_status,json=taskStatus,proto3,oneof"`
}

type AgentMessage_TaskLog struct {
	TaskLog *TaskLogChunk `protobuf:"bytes,3,opt,name=task_log,json=taskLog,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_TaskStatus) isAgentMessage_Payload() {}

func (*AgentMessage_TaskLog) isAgentMessage_Payload() {}

// Sent once when the stream opens. worker_id is empty on first registration.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CpuCores      int32                  `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	RamGb         int32                  `protobuf:"varint,4,opt,name=ram_gb,json=ramGb,proto3" json:"ram_gb,omitempty"`
	GpuCount      int32                  `protobuf:"varint,5,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	GpuModel      string                 `protobuf:"bytes,6,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`
	Os            string                 `protobuf:"bytes,7,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_relayv1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *RegisterRequest) GetRamGb() int32 {
	if x != nil {
		return x.RamGb
	}
	return 0
}

func (x *RegisterRequest) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *RegisterRequest) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

// Sent when a task changes state.
type TaskStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=relay.v1.TaskStatus" json:"status,omitempty"`
	ExitCode      *int32                 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusUpdate) Reset() {
	*x = TaskStatusUpdate{}
	mi := &file_relayv1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdate) ProtoMessage() {}

func (x *TaskStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdate.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdate) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *TaskStatusUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusUpdate) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskStatusUpdate) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *TaskStatusUpdate) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// A chunk of captured output from a running task.
type TaskLogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Stream        LogStream              `protobuf:"varint,2,opt,name=stream,proto3,enum=relay.v1.LogStream" json:"stream,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogChunk) Reset() {
	*x = TaskLogChunk{}
	mi := &file_relayv1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogChunk) ProtoMessage() {}

func (x *TaskLogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogChunk.ProtoReflect.Descriptor instead.
func (*TaskLogChunk) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *TaskLogChunk) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskLogChunk) GetStream() LogStream {
	if x != nil {
		return x.Stream
	}
	return LogStream_LOG_STREAM_UNSPECIFIED
}

func (x *TaskLogChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type CoordinatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CoordinatorMessage_RegisterResponse
	//	*CoordinatorMessage_DispatchTask
	//	*CoordinatorMessage_CancelTask
	Payload       isCoordinatorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_relayv1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *CoordinatorMessage) GetPayload() isCoordinatorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CoordinatorMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetDispatchTask() *DispatchTask {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_DispatchTask); ok {
			return x.DispatchTask
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetCancelTask() *CancelTask {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_CancelTask); ok {
			return x.CancelTask
		}
	}
	return nil
}

type isCoordinatorMessage_Payload interface {
	isCoordinatorMessage_Payload()
}

type CoordinatorMessage_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,1,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type CoordinatorMessage_DispatchTask struct {
	DispatchTask *DispatchTask `protobuf:"bytes,2,opt,name=dispatch_task,json=dispatchTask,proto3,oneof"`
}

type CoordinatorMessage_CancelTask struct {
	CancelTask *CancelTask `protobuf:"bytes,3,opt,name=cancel_task,json=cancelTask,proto3,oneof"`
}

func (*CoordinatorMessage_RegisterResponse) isCoordinatorMessage_Payload() {}

func (*CoordinatorMessage_DispatchTask) isCoordinatorMessage_Payload() {}

func (*CoordinatorMessage_CancelTask) isCoordinatorMessage_Payload() {}

// Sent in response to RegisterRequest; assigns a stable worker ID.
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_relayv1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// Instructs the agent to execute a task.
type DispatchTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId          string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Command        []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispatchTask) Reset() {
	*x = DispatchTask{}
	mi := &file_relayv1_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTask) ProtoMessage() {}

func (x *DispatchTask) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTask.ProtoReflect.Descriptor instead.
func (*DispatchTask) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{6}
}

func (x *DispatchTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DispatchTask) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DispatchTask) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *DispatchTask) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *DispatchTask) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// Instructs the agent to kill a running task.
type CancelTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTask) Reset() {
	*x = CancelTask{}
	mi := &file_relayv1_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTask) ProtoMessage() {}

func (x *CancelTask) ProtoReflect() protoreflect.Message {
	mi := &file_relayv1_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTask.ProtoReflect.Descriptor instead.
func (*CancelTask) Descriptor() ([]byte, []int) {
	return file_relayv1_relay_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_relayv1_relay_proto protoreflect.FileDescriptor

const file_relayv1_relay_proto_rawDesc = "" +
	"\n" +
	"\x13relayv1/relay.proto\x12\brelay.v1\"\xc6\x01\n" +
	"\fAgentMessage\x127\n" +
	"\bregister\x18\x01 \x01(\v2\x19.relay.v1.RegisterRequestH\x00R\bregister\x12=\n" +
	"\vtask_status\x18\x02 \x01(\v2\x1a.relay.v1.TaskStatusUpdateH\x00R\n" +
	"taskStatus\x123\n" +
	"\btask_log\x18\x03 \x01(\v2\x16.relay.v1.TaskLogChunkH\x00R\ataskLogB\t\n" +
	"\apayload\"\xc8\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\x05R\bcpuCores\x12\x15\n" +
	"\x06ram_gb\x18\x04 \x01(\x05R\x05ramGb\x12\x1b\n" +
	"\tgpu_count\x18\x05 \x01(\x05R\bgpuCount\x12\x1b\n" +
	"\tgpu_model\x18\x06 \x01(\tR\bgpuModel\x12\x0e\n" +
	"\x02os\x18\a \x01(\tR\x02os\"\xae\x01\n" +
	"\x10TaskStatusUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.relay.v1.TaskStatusR\x06status\x12 \n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCode\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessageB\f\n" +
	"\n" +
	"_exit_code\"n\n" +
	"\fTaskLogChunk\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12+\n" +
	"\x06stream\x18\x02 \x01(\x0e2\x13.relay.v1.LogStreamR\x06stream\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"\xe2\x01\n" +
	"\x12CoordinatorMessage\x12I\n" +
	"\x11register_response\x18\x01 \x01(\v2\x1a.relay.v1.RegisterResponseH\x00R\x10registerResponse\x12=\n" +
	"\rdispatch_task\x18\x02 \x01(\v2\x16.relay.v1.DispatchTaskH\x00R\fdispatchTask\x127\n" +
	"\vcancel_task\x18\x03 \x01(\v2\x14.relay.v1.CancelTaskH\x00R\n" +
	"cancelTaskB\t\n" +
	"\apayload\"/\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\xec\x01\n" +
	"\fDispatchTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x121\n" +
	"\x03env\x18\x04 \x03(\v2\x1f.relay.v1.DispatchTask.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\n" +
	"CancelTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId*\x8b\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x01\x12\x14\n" +
	"\x10TASK_STATUS_DONE\x10\x02\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_TIMED_OUT\x10\x04*U\n" +
	"\tLogStream\x12\x1a\n" +
	"\x16LOG_STREAM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOG_STREAM_STDOUT\x10\x01\x12\x15\n" +
	"\x11LOG_STREAM_STDERR\x10\x022S\n" +
	"\fAgentService\x12C\n" +
	"\aConnect\x12\x16.relay.v1.AgentMessage\x1a\x1c.relay.v1.CoordinatorMessage(\x010\x01B\x1eZ\x1crelay/internal/proto/relayv1b\x06proto3"

var (
	file_relayv1_relay_proto_rawDescOnce sync.Once
	file_relayv1_relay_proto_rawDescData []byte
)

func file_relayv1_relay_proto_rawDescGZIP() []byte {
	file_relayv1_relay_proto_rawDescOnce.Do(func() {
		file_relayv1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relayv1_relay_proto_rawDesc), len(file_relayv1_relay_proto_rawDesc)))
	})
	return file_relayv1_relay_proto_rawDescData
}

var file_relayv1_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_relayv1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_relayv1_relay_proto_goTypes = []any{
	(TaskStatus)(0),            // 0: relay.v1.TaskStatus
	(LogStream)(0),             // 1: relay.v1.LogStream
	(*AgentMessage)(nil),       // 2: relay.v1.AgentMessage
	(*RegisterRequest)(nil),    // 3: relay.v1.RegisterRequest
	(*TaskStatusUpdate)(nil),   // 4: relay.v1.TaskStatusUpdate
	(*TaskLogChunk)(nil),       // 5: relay.v1.TaskLogChunk
	(*CoordinatorMessage)(nil), // 6: relay.v1.CoordinatorMessage
	(*RegisterResponse)(nil),   // 7: relay.v1.RegisterResponse
	(*DispatchTask)(nil),       // 8: relay.v1.DispatchTask
	(*CancelTask)(nil),         // 9: relay.v1.CancelTask
	nil,                        // 10: relay.v1.DispatchTask.EnvEntry
}
var file_relayv1_relay_proto_depIdxs = []int32{
	3,  // 0: relay.v1.AgentMessage.register:type_name -> relay.v1.RegisterRequest
	4,  // 1: relay.v1.AgentMessage.task_status:type_name -> relay.v1.TaskStatusUpdate
	5,  // 2: relay.v1.AgentMessage.task_log:type_name -> relay.v1.TaskLogChunk
	0,  // 3: relay.v1.TaskStatusUpdate.status:type_name -> relay.v1.TaskStatus
	1,  // 4: relay.v1.TaskLogChunk.stream:type_name -> relay.v1.LogStream
	7,  // 5: relay.v1.CoordinatorMessage.register_response:type_name -> relay.v1.RegisterResponse
	8,  // 6: relay.v1.CoordinatorMessage.dispatch_task:type_name -> relay.v1.DispatchTask
	9,  // 7: relay.v1.CoordinatorMessage.cancel_task:type_name -> relay.v1.CancelTask
	10, // 8: relay.v1.DispatchTask.env:type_name -> relay.v1.DispatchTask.EnvEntry
	2,  // 9: relay.v1.AgentService.Connect:input_type -> relay.v1.AgentMessage
	6,  // 10: relay.v1.AgentService.Connect:output_type -> relay.v1.CoordinatorMessage
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_relayv1_relay_proto_init() }
func file_relayv1_relay_proto_init() {
	if File_relayv1_relay_proto != nil {
		return
	}
	file_relayv1_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_TaskStatus)(nil),
		(*AgentMessage_TaskLog)(nil),
	}
	file_relayv1_relay_proto_msgTypes[2].OneofWrappers = []any{}
	file_relayv1_relay_proto_msgTypes[4].OneofWrappers = []any{
		(*CoordinatorMessage_RegisterResponse)(nil),
		(*CoordinatorMessage_DispatchTask)(nil),
		(*CoordinatorMessage_CancelTask)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relayv1_relay_proto_rawDesc), len(file_relayv1_relay_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relayv1_relay_proto_goTypes,
		DependencyIndexes: file_relayv1_relay_proto_depIdxs,
		EnumInfos:         file_relayv1_relay_proto_enumTypes,
		MessageInfos:      file_relayv1_relay_proto_msgTypes,
	}.Build()
	File_relayv1_relay_proto = out.File
	file_relayv1_relay_proto_goTypes = nil
	file_relayv1_relay_proto_depIdxs = nil
}
