DROP TABLE IF EXISTS reservations;
DROP TABLE IF EXISTS task_logs;
DROP TABLE IF EXISTS task_dependencies;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS workers;
DROP TABLE IF EXISTS api_tokens;
DROP TABLE IF EXISTS users;
