// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_enrollments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAgentEnrollment = `-- name: ConsumeAgentEnrollment :execrows
UPDATE agent_enrollments
SET consumed_at = NOW(), consumed_by = $2
WHERE id = $1 AND consumed_at IS NULL
`

type ConsumeAgentEnrollmentParams struct {
	ID         pgtype.UUID `json:"id"`
	ConsumedBy pgtype.UUID `json:"consumed_by"`
}

// ConsumeAgentEnrollment
//
//	UPDATE agent_enrollments
//	SET consumed_at = NOW(), consumed_by = $2
//	WHERE id = $1 AND consumed_at IS NULL
func (q *Queries) ConsumeAgentEnrollment(ctx context.Context, arg ConsumeAgentEnrollmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeAgentEnrollment, arg.ID, arg.ConsumedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAgentEnrollment = `-- name: CreateAgentEnrollment :one
INSERT INTO agent_enrollments (token_hash, hostname_hint, created_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, token_hash, hostname_hint, created_by, created_at, expires_at, consumed_at, consumed_by
`

type CreateAgentEnrollmentParams struct {
	TokenHash    string             `json:"token_hash"`
	HostnameHint *string            `json:"hostname_hint"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

// CreateAgentEnrollment
//
//	INSERT INTO agent_enrollments (token_hash, hostname_hint, created_by, expires_at)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, token_hash, hostname_hint, created_by, created_at, expires_at, consumed_at, consumed_by
func (q *Queries) CreateAgentEnrollment(ctx context.Context, arg CreateAgentEnrollmentParams) (AgentEnrollment, error) {
	row := q.db.QueryRow(ctx, createAgentEnrollment,
		arg.TokenHash,
		arg.HostnameHint,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i AgentEnrollment
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.HostnameHint,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedBy,
	)
	return i, err
}

const deleteExpiredAgentEnrollments = `-- name: DeleteExpiredAgentEnrollments :execrows
DELETE FROM agent_enrollments WHERE expires_at <= NOW() AND consumed_at IS NULL
`

// DeleteExpiredAgentEnrollments
//
//	DELETE FROM agent_enrollments WHERE expires_at <= NOW() AND consumed_at IS NULL
func (q *Queries) DeleteExpiredAgentEnrollments(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAgentEnrollments)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentEnrollmentByTokenHash = `-- name: GetAgentEnrollmentByTokenHash :one
SELECT id, token_hash, hostname_hint, created_by, created_at, expires_at, consumed_at, consumed_by FROM agent_enrollments WHERE token_hash = $1
`

// GetAgentEnrollmentByTokenHash
//
//	SELECT id, token_hash, hostname_hint, created_by, created_at, expires_at, consumed_at, consumed_by FROM agent_enrollments WHERE token_hash = $1
func (q *Queries) GetAgentEnrollmentByTokenHash(ctx context.Context, tokenHash string) (AgentEnrollment, error) {
	row := q.db.QueryRow(ctx, getAgentEnrollmentByTokenHash, tokenHash)
	var i AgentEnrollment
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.HostnameHint,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedBy,
	)
	return i, err
}

const listActiveAgentEnrollments = `-- name: ListActiveAgentEnrollments :many
SELECT id, hostname_hint, created_by, created_at, expires_at
FROM agent_enrollments
WHERE consumed_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
`

type ListActiveAgentEnrollmentsRow struct {
	ID           pgtype.UUID        `json:"id"`
	HostnameHint *string            `json:"hostname_hint"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

// ListActiveAgentEnrollments
//
//	SELECT id, hostname_hint, created_by, created_at, expires_at
//	FROM agent_enrollments
//	WHERE consumed_at IS NULL AND expires_at > NOW()
//	ORDER BY created_at DESC
func (q *Queries) ListActiveAgentEnrollments(ctx context.Context) ([]ListActiveAgentEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAgentEnrollments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAgentEnrollmentsRow
	for rows.Next() {
		var i ListActiveAgentEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.HostnameHint,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
