// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (token_hash, email, created_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, token_hash, email, created_by, created_at, expires_at, used_at, used_by
`

type CreateInviteParams struct {
	TokenHash string             `json:"token_hash"`
	Email     *string            `json:"email"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// CreateInvite
//
//	INSERT INTO invites (token_hash, email, created_by, expires_at)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, token_hash, email, created_by, created_at, expires_at, used_at, used_by
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.TokenHash,
		arg.Email,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, token_hash, email, created_by, created_at, expires_at, used_at, used_by FROM invites WHERE token_hash = $1
`

// GetInviteByTokenHash
//
//	SELECT id, token_hash, email, created_by, created_at, expires_at, used_at, used_by FROM invites WHERE token_hash = $1
func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const markInviteUsed = `-- name: MarkInviteUsed :execrows
UPDATE invites
SET used_at = NOW(), used_by = $2
WHERE id = $1 AND used_at IS NULL
`

type MarkInviteUsedParams struct {
	ID     pgtype.UUID `json:"id"`
	UsedBy pgtype.UUID `json:"used_by"`
}

// MarkInviteUsed
//
//	UPDATE invites
//	SET used_at = NOW(), used_by = $2
//	WHERE id = $1 AND used_at IS NULL
func (q *Queries) MarkInviteUsed(ctx context.Context, arg MarkInviteUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInviteUsed, arg.ID, arg.UsedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
