// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobs = `-- name: CountJobs :one
SELECT COUNT(*) FROM jobs
`

// CountJobs
//
//	SELECT COUNT(*) FROM jobs
func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobsByScheduledJob = `-- name: CountJobsByScheduledJob :one
SELECT COUNT(*) FROM jobs WHERE scheduled_job_id = $1
`

// CountJobsByScheduledJob
//
//	SELECT COUNT(*) FROM jobs WHERE scheduled_job_id = $1
func (q *Queries) CountJobsByScheduledJob(ctx context.Context, scheduledJobID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsByScheduledJob, scheduledJobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobsByStatus = `-- name: CountJobsByStatus :one
SELECT COUNT(*) FROM jobs WHERE status = $1
`

// CountJobsByStatus
//
//	SELECT COUNT(*) FROM jobs WHERE status = $1
func (q *Queries) CountJobsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (name, priority, submitted_by, labels, scheduled_job_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, priority, status, submitted_by, labels, created_at, updated_at, scheduled_job_id
`

type CreateJobParams struct {
	Name           string      `json:"name"`
	Priority       string      `json:"priority"`
	SubmittedBy    pgtype.UUID `json:"submitted_by"`
	Labels         []byte      `json:"labels"`
	ScheduledJobID pgtype.UUID `json:"scheduled_job_id"`
}

// CreateJob
//
//	INSERT INTO jobs (name, priority, submitted_by, labels, scheduled_job_id)
//	VALUES ($1, $2, $3, $4, $5)
//	RETURNING id, name, priority, status, submitted_by, labels, created_at, updated_at, scheduled_job_id
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Name,
		arg.Priority,
		arg.SubmittedBy,
		arg.Labels,
		arg.ScheduledJobID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.Status,
		&i.SubmittedBy,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledJobID,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = $1
`

// DeleteJob
//
//	DELETE FROM jobs WHERE id = $1
func (q *Queries) DeleteJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, name, priority, status, submitted_by, labels, created_at, updated_at, scheduled_job_id FROM jobs WHERE id = $1
`

// GetJob
//
//	SELECT id, name, priority, status, submitted_by, labels, created_at, updated_at, scheduled_job_id FROM jobs WHERE id = $1
func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.Status,
		&i.SubmittedBy,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledJobID,
	)
	return i, err
}

const getJobWithEmail = `-- name: GetJobWithEmail :one
SELECT j.id, j.name, j.priority, j.status, j.submitted_by, j.labels, j.created_at, j.updated_at, j.scheduled_job_id, u.email AS submitted_by_email
FROM jobs j
JOIN users u ON u.id = j.submitted_by
WHERE j.id = $1
`

type GetJobWithEmailRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Priority         string             `json:"priority"`
	Status           string             `json:"status"`
	SubmittedBy      pgtype.UUID        `json:"submitted_by"`
	Labels           []byte             `json:"labels"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ScheduledJobID   pgtype.UUID        `json:"scheduled_job_id"`
	SubmittedByEmail string             `json:"submitted_by_email"`
}

// GetJobWithEmail
//
//	SELECT j.id, j.name, j.priority, j.status, j.submitted_by, j.labels, j.created_at, j.updated_at, j.scheduled_job_id, u.email AS submitted_by_email
//	FROM jobs j
//	JOIN users u ON u.id = j.submitted_by
//	WHERE j.id = $1
func (q *Queries) GetJobWithEmail(ctx context.Context, id pgtype.UUID) (GetJobWithEmailRow, error) {
	row := q.db.QueryRow(ctx, getJobWithEmail, id)
	var i GetJobWithEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.Status,
		&i.SubmittedBy,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledJobID,
		&i.SubmittedByEmail,
	)
	return i, err
}

const listJobsByScheduledJob = `-- name: ListJobsByScheduledJob :many
SELECT j.id, j.name, j.priority, j.status, j.submitted_by, j.labels, j.created_at, j.updated_at, j.scheduled_job_id, u.email AS submitted_by_email
FROM jobs j
JOIN users u ON u.id = j.submitted_by
WHERE j.scheduled_job_id = $1
ORDER BY j.created_at DESC
`

type ListJobsByScheduledJobRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Priority         string             `json:"priority"`
	Status           string             `json:"status"`
	SubmittedBy      pgtype.UUID        `json:"submitted_by"`
	Labels           []byte             `json:"labels"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ScheduledJobID   pgtype.UUID        `json:"scheduled_job_id"`
	SubmittedByEmail string             `json:"submitted_by_email"`
}

// Internal use only (schedrunner tests). Not paginated.
//
//	SELECT j.id, j.name, j.priority, j.status, j.submitted_by, j.labels, j.created_at, j.updated_at, j.scheduled_job_id, u.email AS submitted_by_email
//	FROM jobs j
//	JOIN users u ON u.id = j.submitted_by
//	WHERE j.scheduled_job_id = $1
//	ORDER BY j.created_at DESC
func (q *Queries) ListJobsByScheduledJob(ctx context.Context, scheduledJobID pgtype.UUID) ([]ListJobsByScheduledJobRow, error) {
	rows, err := q.db.Query(ctx, listJobsByScheduledJob, scheduledJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsByScheduledJobRow
	for rows.Next() {
		var i ListJobsByScheduledJobRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.Status,
			&i.SubmittedBy,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduledJobID,
			&i.SubmittedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByScheduledJobWithEmailPage = `-- name: ListJobsByScheduledJobWithEmailPage :many
SELECT j.id, j.name, j.priority, j.status, j.submitted_by, j.labels, j.created_at, j.updated_at, j.scheduled_job_id, u.email AS submitted_by_email
FROM jobs j
JOIN users u ON u.id = j.submitted_by
WHERE j.scheduled_job_id = $1::uuid
  AND ($2::bool = FALSE
       OR (j.created_at, j.id) < ($3::timestamptz, $4::uuid))
ORDER BY j.created_at DESC, j.id DESC
LIMIT $5::int + 1
`

type ListJobsByScheduledJobWithEmailPageParams struct {
	ScheduledJobID pgtype.UUID        `json:"scheduled_job_id"`
	CursorSet      bool               `json:"cursor_set"`
	CursorTs       pgtype.Timestamptz `json:"cursor_ts"`
	CursorID       pgtype.UUID        `json:"cursor_id"`
	PageLimit      int32              `json:"page_limit"`
}

type ListJobsByScheduledJobWithEmailPageRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Priority         string             `json:"priority"`
	Status           string             `json:"status"`
	SubmittedBy      pgtype.UUID        `json:"submitted_by"`
	Labels           []byte             `json:"labels"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ScheduledJobID   pgtype.UUID        `json:"scheduled_job_id"`
	SubmittedByEmail string             `json:"submitted_by_email"`
}

// ListJobsByScheduledJobWithEmailPage
//
//	SELECT j.id, j.name, j.priority, j.status, j.submitted_by, j.labels, j.created_at, j.updated_at, j.scheduled_job_id, u.email AS submitted_by_email
//	FROM jobs j
//	JOIN users u ON u.id = j.submitted_by
//	WHERE j.scheduled_job_id = $1::uuid
//	  AND ($2::bool = FALSE
//	       OR (j.created_at, j.id) < ($3::timestamptz, $4::uuid))
//	ORDER BY j.created_at DESC, j.id DESC
//	LIMIT $5::int + 1
func (q *Queries) ListJobsByScheduledJobWithEmailPage(ctx context.Context, arg ListJobsByScheduledJobWithEmailPageParams) ([]ListJobsByScheduledJobWithEmailPageRow, error) {
	rows, err := q.db.Query(ctx, listJobsByScheduledJobWithEmailPage,
		arg.ScheduledJobID,
		arg.CursorSet,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsByScheduledJobWithEmailPageRow
	for rows.Next() {
		var i ListJobsByScheduledJobWithEmailPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.Status,
			&i.SubmittedBy,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduledJobID,
			&i.SubmittedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatusWithEmailPage = `-- name: ListJobsByStatusWithEmailPage :many
SELECT j.id, j.name, j.priority, j.status, j.submitted_by, j.labels, j.created_at, j.updated_at, j.scheduled_job_id, u.email AS submitted_by_email
FROM jobs j
JOIN users u ON u.id = j.submitted_by
WHERE j.status = $1::text
  AND ($2::bool = FALSE
       OR (j.created_at, j.id) < ($3::timestamptz, $4::uuid))
ORDER BY j.created_at DESC, j.id DESC
LIMIT $5::int + 1
`

type ListJobsByStatusWithEmailPageParams struct {
	Status    string             `json:"status"`
	CursorSet bool               `json:"cursor_set"`
	CursorTs  pgtype.Timestamptz `json:"cursor_ts"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	PageLimit int32              `json:"page_limit"`
}

type ListJobsByStatusWithEmailPageRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Priority         string             `json:"priority"`
	Status           string             `json:"status"`
	SubmittedBy      pgtype.UUID        `json:"submitted_by"`
	Labels           []byte             `json:"labels"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ScheduledJobID   pgtype.UUID        `json:"scheduled_job_id"`
	SubmittedByEmail string             `json:"submitted_by_email"`
}

// ListJobsByStatusWithEmailPage
//
//	SELECT j.id, j.name, j.priority, j.status, j.submitted_by, j.labels, j.created_at, j.updated_at, j.scheduled_job_id, u.email AS submitted_by_email
//	FROM jobs j
//	JOIN users u ON u.id = j.submitted_by
//	WHERE j.status = $1::text
//	  AND ($2::bool = FALSE
//	       OR (j.created_at, j.id) < ($3::timestamptz, $4::uuid))
//	ORDER BY j.created_at DESC, j.id DESC
//	LIMIT $5::int + 1
func (q *Queries) ListJobsByStatusWithEmailPage(ctx context.Context, arg ListJobsByStatusWithEmailPageParams) ([]ListJobsByStatusWithEmailPageRow, error) {
	rows, err := q.db.Query(ctx, listJobsByStatusWithEmailPage,
		arg.Status,
		arg.CursorSet,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsByStatusWithEmailPageRow
	for rows.Next() {
		var i ListJobsByStatusWithEmailPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.Status,
			&i.SubmittedBy,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduledJobID,
			&i.SubmittedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsWithEmailPage = `-- name: ListJobsWithEmailPage :many
SELECT j.id, j.name, j.priority, j.status, j.submitted_by, j.labels, j.created_at, j.updated_at, j.scheduled_job_id, u.email AS submitted_by_email
FROM jobs j
JOIN users u ON u.id = j.submitted_by
WHERE ($1::bool = FALSE
       OR (j.created_at, j.id) < ($2::timestamptz, $3::uuid))
ORDER BY j.created_at DESC, j.id DESC
LIMIT $4::int + 1
`

type ListJobsWithEmailPageParams struct {
	CursorSet bool               `json:"cursor_set"`
	CursorTs  pgtype.Timestamptz `json:"cursor_ts"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	PageLimit int32              `json:"page_limit"`
}

type ListJobsWithEmailPageRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Priority         string             `json:"priority"`
	Status           string             `json:"status"`
	SubmittedBy      pgtype.UUID        `json:"submitted_by"`
	Labels           []byte             `json:"labels"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ScheduledJobID   pgtype.UUID        `json:"scheduled_job_id"`
	SubmittedByEmail string             `json:"submitted_by_email"`
}

// ListJobsWithEmailPage
//
//	SELECT j.id, j.name, j.priority, j.status, j.submitted_by, j.labels, j.created_at, j.updated_at, j.scheduled_job_id, u.email AS submitted_by_email
//	FROM jobs j
//	JOIN users u ON u.id = j.submitted_by
//	WHERE ($1::bool = FALSE
//	       OR (j.created_at, j.id) < ($2::timestamptz, $3::uuid))
//	ORDER BY j.created_at DESC, j.id DESC
//	LIMIT $4::int + 1
func (q *Queries) ListJobsWithEmailPage(ctx context.Context, arg ListJobsWithEmailPageParams) ([]ListJobsWithEmailPageRow, error) {
	rows, err := q.db.Query(ctx, listJobsWithEmailPage,
		arg.CursorSet,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsWithEmailPageRow
	for rows.Next() {
		var i ListJobsWithEmailPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.Status,
			&i.SubmittedBy,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduledJobID,
			&i.SubmittedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, priority, status, submitted_by, labels, created_at, updated_at, scheduled_job_id
`

type UpdateJobStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// UpdateJobStatus
//
//	UPDATE jobs
//	SET status = $2, updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, name, priority, status, submitted_by, labels, created_at, updated_at, scheduled_job_id
func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.Status,
		&i.SubmittedBy,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledJobID,
	)
	return i, err
}
