// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (name, priority, submitted_by, labels)
VALUES ($1, $2, $3, $4)
RETURNING id, name, priority, status, submitted_by, labels, created_at, updated_at
`

type CreateJobParams struct {
	Name        string          `json:"name"`
	Priority    string          `json:"priority"`
	SubmittedBy uuid.UUID       `json:"submitted_by"`
	Labels      json.RawMessage `json:"labels"`
}

// CreateJob
//
//	INSERT INTO jobs (name, priority, submitted_by, labels)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, name, priority, status, submitted_by, labels, created_at, updated_at
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.Name,
		arg.Priority,
		arg.SubmittedBy,
		arg.Labels,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.Status,
		&i.SubmittedBy,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = $1
`

// DeleteJob
//
//	DELETE FROM jobs WHERE id = $1
func (q *Queries) DeleteJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, name, priority, status, submitted_by, labels, created_at, updated_at FROM jobs WHERE id = $1
`

// GetJob
//
//	SELECT id, name, priority, status, submitted_by, labels, created_at, updated_at FROM jobs WHERE id = $1
func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.Status,
		&i.SubmittedBy,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, name, priority, status, submitted_by, labels, created_at, updated_at FROM jobs ORDER BY created_at DESC
`

// ListJobs
//
//	SELECT id, name, priority, status, submitted_by, labels, created_at, updated_at FROM jobs ORDER BY created_at DESC
func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.Status,
			&i.SubmittedBy,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT id, name, priority, status, submitted_by, labels, created_at, updated_at FROM jobs WHERE status = $1 ORDER BY created_at DESC
`

// ListJobsByStatus
//
//	SELECT id, name, priority, status, submitted_by, labels, created_at, updated_at FROM jobs WHERE status = $1 ORDER BY created_at DESC
func (q *Queries) ListJobsByStatus(ctx context.Context, status string) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.Status,
			&i.SubmittedBy,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, priority, status, submitted_by, labels, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// UpdateJobStatus
//
//	UPDATE jobs
//	SET status = $2, updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, name, priority, status, submitted_by, labels, created_at, updated_at
func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.Status,
		&i.SubmittedBy,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
