// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentEnrollment struct {
	ID           pgtype.UUID        `json:"id"`
	TokenHash    string             `json:"token_hash"`
	HostnameHint *string            `json:"hostname_hint"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedBy   pgtype.UUID        `json:"consumed_by"`
}

type ApiToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Invite struct {
	ID        pgtype.UUID        `json:"id"`
	TokenHash string             `json:"token_hash"`
	Email     *string            `json:"email"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	UsedBy    pgtype.UUID        `json:"used_by"`
}

type Job struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Priority    string             `json:"priority"`
	Status      string             `json:"status"`
	SubmittedBy pgtype.UUID        `json:"submitted_by"`
	Labels      []byte             `json:"labels"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Reservation struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Selector  []byte             `json:"selector"`
	WorkerIds []pgtype.UUID      `json:"worker_ids"`
	UserID    pgtype.UUID        `json:"user_id"`
	Project   *string            `json:"project"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID              pgtype.UUID        `json:"id"`
	JobID           pgtype.UUID        `json:"job_id"`
	Name            string             `json:"name"`
	Command         []string           `json:"command"`
	Env             []byte             `json:"env"`
	Requires        []byte             `json:"requires"`
	TimeoutSeconds  *int32             `json:"timeout_seconds"`
	Retries         int32              `json:"retries"`
	RetryCount      int32              `json:"retry_count"`
	Status          string             `json:"status"`
	WorkerID        pgtype.UUID        `json:"worker_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	AssignmentEpoch int32              `json:"assignment_epoch"`
}

type TaskDependency struct {
	TaskID          pgtype.UUID `json:"task_id"`
	DependsOnTaskID pgtype.UUID `json:"depends_on_task_id"`
}

type TaskLog struct {
	ID        int64              `json:"id"`
	TaskID    pgtype.UUID        `json:"task_id"`
	Stream    string             `json:"stream"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	IsAdmin      bool               `json:"is_admin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PasswordHash string             `json:"password_hash"`
}

type Worker struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Hostname       string             `json:"hostname"`
	CpuCores       int32              `json:"cpu_cores"`
	RamGb          int32              `json:"ram_gb"`
	GpuCount       int32              `json:"gpu_count"`
	GpuModel       string             `json:"gpu_model"`
	Os             string             `json:"os"`
	MaxSlots       int32              `json:"max_slots"`
	Labels         []byte             `json:"labels"`
	Status         string             `json:"status"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AgentTokenHash *string            `json:"agent_token_hash"`
}
