// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReservations = `-- name: CountReservations :one
SELECT COUNT(*) FROM reservations
`

// CountReservations
//
//	SELECT COUNT(*) FROM reservations
func (q *Queries) CountReservations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countReservations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (name, selector, worker_ids, user_id, project, starts_at, ends_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, selector, worker_ids, user_id, project, starts_at, ends_at, created_at
`

type CreateReservationParams struct {
	Name      string             `json:"name"`
	Selector  []byte             `json:"selector"`
	WorkerIds []pgtype.UUID      `json:"worker_ids"`
	UserID    pgtype.UUID        `json:"user_id"`
	Project   *string            `json:"project"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
}

// CreateReservation
//
//	INSERT INTO reservations (name, selector, worker_ids, user_id, project, starts_at, ends_at)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, name, selector, worker_ids, user_id, project, starts_at, ends_at, created_at
func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.Name,
		arg.Selector,
		arg.WorkerIds,
		arg.UserID,
		arg.Project,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Selector,
		&i.WorkerIds,
		&i.UserID,
		&i.Project,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReservation = `-- name: DeleteReservation :exec
DELETE FROM reservations WHERE id = $1
`

// DeleteReservation
//
//	DELETE FROM reservations WHERE id = $1
func (q *Queries) DeleteReservation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReservation, id)
	return err
}

const getReservation = `-- name: GetReservation :one
SELECT id, name, selector, worker_ids, user_id, project, starts_at, ends_at, created_at FROM reservations WHERE id = $1
`

// GetReservation
//
//	SELECT id, name, selector, worker_ids, user_id, project, starts_at, ends_at, created_at FROM reservations WHERE id = $1
func (q *Queries) GetReservation(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Selector,
		&i.WorkerIds,
		&i.UserID,
		&i.Project,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveReservations = `-- name: ListActiveReservations :many
SELECT id, name, selector, worker_ids, user_id, project, starts_at, ends_at, created_at FROM reservations
WHERE (ends_at IS NULL OR ends_at > NOW())
  AND (starts_at IS NULL OR starts_at <= NOW())
ORDER BY created_at
`

// ListActiveReservations
//
//	SELECT id, name, selector, worker_ids, user_id, project, starts_at, ends_at, created_at FROM reservations
//	WHERE (ends_at IS NULL OR ends_at > NOW())
//	  AND (starts_at IS NULL OR starts_at <= NOW())
//	ORDER BY created_at
func (q *Queries) ListActiveReservations(ctx context.Context) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listActiveReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Selector,
			&i.WorkerIds,
			&i.UserID,
			&i.Project,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsPage = `-- name: ListReservationsPage :many
SELECT id, name, selector, worker_ids, user_id, project, starts_at, ends_at, created_at FROM reservations
WHERE ($1::bool = FALSE
       OR (created_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4::int + 1
`

type ListReservationsPageParams struct {
	CursorSet bool               `json:"cursor_set"`
	CursorTs  pgtype.Timestamptz `json:"cursor_ts"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	PageLimit int32              `json:"page_limit"`
}

// ListReservationsPage
//
//	SELECT id, name, selector, worker_ids, user_id, project, starts_at, ends_at, created_at FROM reservations
//	WHERE ($1::bool = FALSE
//	       OR (created_at, id) < ($2::timestamptz, $3::uuid))
//	ORDER BY created_at DESC, id DESC
//	LIMIT $4::int + 1
func (q *Queries) ListReservationsPage(ctx context.Context, arg ListReservationsPageParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsPage,
		arg.CursorSet,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Selector,
			&i.WorkerIds,
			&i.UserID,
			&i.Project,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
