// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduled_jobs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceScheduledJob = `-- name: AdvanceScheduledJob :exec
UPDATE scheduled_jobs
SET next_run_at = $2,
    last_run_at = NOW(),
    last_job_id = COALESCE($3, last_job_id),
    updated_at  = NOW()
WHERE id = $1
`

type AdvanceScheduledJobParams struct {
	ID        pgtype.UUID        `json:"id"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
	LastJobID pgtype.UUID        `json:"last_job_id"`
}

// AdvanceScheduledJob
//
//	UPDATE scheduled_jobs
//	SET next_run_at = $2,
//	    last_run_at = NOW(),
//	    last_job_id = COALESCE($3, last_job_id),
//	    updated_at  = NOW()
//	WHERE id = $1
func (q *Queries) AdvanceScheduledJob(ctx context.Context, arg AdvanceScheduledJobParams) error {
	_, err := q.db.Exec(ctx, advanceScheduledJob, arg.ID, arg.NextRunAt, arg.LastJobID)
	return err
}

const countActiveJobsForSchedule = `-- name: CountActiveJobsForSchedule :one
SELECT COUNT(*) FROM jobs
 WHERE scheduled_job_id = $1
   AND status IN ('pending','queued','running','dispatched')
`

// CountActiveJobsForSchedule
//
//	SELECT COUNT(*) FROM jobs
//	 WHERE scheduled_job_id = $1
//	   AND status IN ('pending','queued','running','dispatched')
func (q *Queries) CountActiveJobsForSchedule(ctx context.Context, scheduledJobID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveJobsForSchedule, scheduledJobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScheduledJob = `-- name: CreateScheduledJob :one
INSERT INTO scheduled_jobs (
    name, owner_id, cron_expr, timezone, job_spec,
    overlap_policy, enabled, next_run_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at
`

type CreateScheduledJobParams struct {
	Name          string             `json:"name"`
	OwnerID       pgtype.UUID        `json:"owner_id"`
	CronExpr      string             `json:"cron_expr"`
	Timezone      string             `json:"timezone"`
	JobSpec       []byte             `json:"job_spec"`
	OverlapPolicy string             `json:"overlap_policy"`
	Enabled       bool               `json:"enabled"`
	NextRunAt     pgtype.Timestamptz `json:"next_run_at"`
}

// CreateScheduledJob
//
//	INSERT INTO scheduled_jobs (
//	    name, owner_id, cron_expr, timezone, job_spec,
//	    overlap_policy, enabled, next_run_at
//	) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
//	RETURNING id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at
func (q *Queries) CreateScheduledJob(ctx context.Context, arg CreateScheduledJobParams) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, createScheduledJob,
		arg.Name,
		arg.OwnerID,
		arg.CronExpr,
		arg.Timezone,
		arg.JobSpec,
		arg.OverlapPolicy,
		arg.Enabled,
		arg.NextRunAt,
	)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CronExpr,
		&i.Timezone,
		&i.JobSpec,
		&i.OverlapPolicy,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastJobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScheduledJob = `-- name: DeleteScheduledJob :execrows
DELETE FROM scheduled_jobs WHERE id = $1
`

// DeleteScheduledJob
//
//	DELETE FROM scheduled_jobs WHERE id = $1
func (q *Queries) DeleteScheduledJob(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScheduledJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScheduledJob = `-- name: GetScheduledJob :one
SELECT id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at FROM scheduled_jobs WHERE id = $1
`

// GetScheduledJob
//
//	SELECT id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at FROM scheduled_jobs WHERE id = $1
func (q *Queries) GetScheduledJob(ctx context.Context, id pgtype.UUID) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, getScheduledJob, id)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CronExpr,
		&i.Timezone,
		&i.JobSpec,
		&i.OverlapPolicy,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastJobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEligibleScheduledJobs = `-- name: ListEligibleScheduledJobs :many
SELECT id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at FROM scheduled_jobs
 WHERE enabled
   AND next_run_at <= NOW()
 ORDER BY next_run_at ASC
 LIMIT $1
 FOR UPDATE SKIP LOCKED
`

// ListEligibleScheduledJobs
//
//	SELECT id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at FROM scheduled_jobs
//	 WHERE enabled
//	   AND next_run_at <= NOW()
//	 ORDER BY next_run_at ASC
//	 LIMIT $1
//	 FOR UPDATE SKIP LOCKED
func (q *Queries) ListEligibleScheduledJobs(ctx context.Context, limit int32) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, listEligibleScheduledJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledJob
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CronExpr,
			&i.Timezone,
			&i.JobSpec,
			&i.OverlapPolicy,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastJobID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueScheduledJobsForCatchup = `-- name: ListOverdueScheduledJobsForCatchup :many
SELECT id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at FROM scheduled_jobs
 WHERE enabled
   AND next_run_at < NOW()
`

// ListOverdueScheduledJobsForCatchup
//
//	SELECT id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at FROM scheduled_jobs
//	 WHERE enabled
//	   AND next_run_at < NOW()
func (q *Queries) ListOverdueScheduledJobsForCatchup(ctx context.Context) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, listOverdueScheduledJobsForCatchup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledJob
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CronExpr,
			&i.Timezone,
			&i.JobSpec,
			&i.OverlapPolicy,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastJobID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledJobs = `-- name: ListScheduledJobs :many
SELECT id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at FROM scheduled_jobs ORDER BY created_at DESC
`

// ListScheduledJobs
//
//	SELECT id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at FROM scheduled_jobs ORDER BY created_at DESC
func (q *Queries) ListScheduledJobs(ctx context.Context) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, listScheduledJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledJob
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CronExpr,
			&i.Timezone,
			&i.JobSpec,
			&i.OverlapPolicy,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastJobID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledJobsByOwner = `-- name: ListScheduledJobsByOwner :many
SELECT id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at FROM scheduled_jobs WHERE owner_id = $1 ORDER BY created_at DESC
`

// ListScheduledJobsByOwner
//
//	SELECT id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at FROM scheduled_jobs WHERE owner_id = $1 ORDER BY created_at DESC
func (q *Queries) ListScheduledJobsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, listScheduledJobsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledJob
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CronExpr,
			&i.Timezone,
			&i.JobSpec,
			&i.OverlapPolicy,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastJobID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduledJob = `-- name: UpdateScheduledJob :one
UPDATE scheduled_jobs
SET name           = $2,
    cron_expr      = $3,
    timezone       = $4,
    job_spec       = $5,
    overlap_policy = $6,
    enabled        = $7,
    next_run_at    = $8,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at
`

type UpdateScheduledJobParams struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	CronExpr      string             `json:"cron_expr"`
	Timezone      string             `json:"timezone"`
	JobSpec       []byte             `json:"job_spec"`
	OverlapPolicy string             `json:"overlap_policy"`
	Enabled       bool               `json:"enabled"`
	NextRunAt     pgtype.Timestamptz `json:"next_run_at"`
}

// UpdateScheduledJob
//
//	UPDATE scheduled_jobs
//	SET name           = $2,
//	    cron_expr      = $3,
//	    timezone       = $4,
//	    job_spec       = $5,
//	    overlap_policy = $6,
//	    enabled        = $7,
//	    next_run_at    = $8,
//	    updated_at     = NOW()
//	WHERE id = $1
//	RETURNING id, name, owner_id, cron_expr, timezone, job_spec, overlap_policy, enabled, next_run_at, last_run_at, last_job_id, created_at, updated_at
func (q *Queries) UpdateScheduledJob(ctx context.Context, arg UpdateScheduledJobParams) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, updateScheduledJob,
		arg.ID,
		arg.Name,
		arg.CronExpr,
		arg.Timezone,
		arg.JobSpec,
		arg.OverlapPolicy,
		arg.Enabled,
		arg.NextRunAt,
	)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CronExpr,
		&i.Timezone,
		&i.JobSpec,
		&i.OverlapPolicy,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastJobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
