// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendTaskLog = `-- name: AppendTaskLog :exec
INSERT INTO task_logs (task_id, stream, content)
SELECT $1, $2, $3
WHERE EXISTS (
    SELECT 1 FROM tasks WHERE id = $1 AND assignment_epoch = $4
)
`

type AppendTaskLogParams struct {
	TaskID          pgtype.UUID `json:"task_id"`
	Stream          string      `json:"stream"`
	Content         string      `json:"content"`
	AssignmentEpoch int32       `json:"assignment_epoch"`
}

// Inserts a log chunk only if the caller's epoch matches the task's current
// assignment. Stale chunks (from a reassigned generation) silently insert
// zero rows.
//
//	INSERT INTO task_logs (task_id, stream, content)
//	SELECT $1, $2, $3
//	WHERE EXISTS (
//	    SELECT 1 FROM tasks WHERE id = $1 AND assignment_epoch = $4
//	)
func (q *Queries) AppendTaskLog(ctx context.Context, arg AppendTaskLogParams) error {
	_, err := q.db.Exec(ctx, appendTaskLog,
		arg.TaskID,
		arg.Stream,
		arg.Content,
		arg.AssignmentEpoch,
	)
	return err
}

const claimTaskForWorker = `-- name: ClaimTaskForWorker :one
UPDATE tasks
SET status = 'dispatched',
    worker_id = $2,
    assignment_epoch = assignment_epoch + 1
WHERE id = $1 AND status = 'pending'
RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
`

type ClaimTaskForWorkerParams struct {
	ID       pgtype.UUID `json:"id"`
	WorkerID pgtype.UUID `json:"worker_id"`
}

// Atomically transition a pending task to 'dispatched' on the given worker.
// Increments assignment_epoch so subsequent status updates from prior
// generations can be rejected. Returns pgx.ErrNoRows if the task is no longer
// pending (another dispatcher already claimed it, or the row vanished).
//
//	UPDATE tasks
//	SET status = 'dispatched',
//	    worker_id = $2,
//	    assignment_epoch = assignment_epoch + 1
//	WHERE id = $1 AND status = 'pending'
//	RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
func (q *Queries) ClaimTaskForWorker(ctx context.Context, arg ClaimTaskForWorkerParams) (Task, error) {
	row := q.db.QueryRow(ctx, claimTaskForWorker, arg.ID, arg.WorkerID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}

const countActiveTasksByAllWorkers = `-- name: CountActiveTasksByAllWorkers :many
SELECT worker_id, count(*)::bigint AS active
FROM tasks
WHERE worker_id IS NOT NULL
  AND status IN ('dispatched', 'running')
GROUP BY worker_id
`

type CountActiveTasksByAllWorkersRow struct {
	WorkerID pgtype.UUID `json:"worker_id"`
	Active   int64       `json:"active"`
}

// Per-worker count of non-terminal tasks. Used by the dispatcher to compute
// available slots in one query rather than N per cycle.
//
//	SELECT worker_id, count(*)::bigint AS active
//	FROM tasks
//	WHERE worker_id IS NOT NULL
//	  AND status IN ('dispatched', 'running')
//	GROUP BY worker_id
func (q *Queries) CountActiveTasksByAllWorkers(ctx context.Context) ([]CountActiveTasksByAllWorkersRow, error) {
	rows, err := q.db.Query(ctx, countActiveTasksByAllWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountActiveTasksByAllWorkersRow
	for rows.Next() {
		var i CountActiveTasksByAllWorkersRow
		if err := rows.Scan(&i.WorkerID, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (job_id, name, commands, env, requires, timeout_seconds, retries)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
`

type CreateTaskParams struct {
	JobID          pgtype.UUID `json:"job_id"`
	Name           string      `json:"name"`
	Commands       []byte      `json:"commands"`
	Env            []byte      `json:"env"`
	Requires       []byte      `json:"requires"`
	TimeoutSeconds *int32      `json:"timeout_seconds"`
	Retries        int32       `json:"retries"`
}

// CreateTask
//
//	INSERT INTO tasks (job_id, name, commands, env, requires, timeout_seconds, retries)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.JobID,
		arg.Name,
		arg.Commands,
		arg.Env,
		arg.Requires,
		arg.TimeoutSeconds,
		arg.Retries,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}

const createTaskDependency = `-- name: CreateTaskDependency :exec
INSERT INTO task_dependencies (task_id, depends_on_task_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateTaskDependencyParams struct {
	TaskID          pgtype.UUID `json:"task_id"`
	DependsOnTaskID pgtype.UUID `json:"depends_on_task_id"`
}

// CreateTaskDependency
//
//	INSERT INTO task_dependencies (task_id, depends_on_task_id)
//	VALUES ($1, $2)
//	ON CONFLICT DO NOTHING
func (q *Queries) CreateTaskDependency(ctx context.Context, arg CreateTaskDependencyParams) error {
	_, err := q.db.Exec(ctx, createTaskDependency, arg.TaskID, arg.DependsOnTaskID)
	return err
}

const createTaskWithSource = `-- name: CreateTaskWithSource :one
INSERT INTO tasks (job_id, name, commands, env, requires, timeout_seconds, retries, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
`

type CreateTaskWithSourceParams struct {
	JobID          pgtype.UUID `json:"job_id"`
	Name           string      `json:"name"`
	Commands       []byte      `json:"commands"`
	Env            []byte      `json:"env"`
	Requires       []byte      `json:"requires"`
	TimeoutSeconds *int32      `json:"timeout_seconds"`
	Retries        int32       `json:"retries"`
	Source         []byte      `json:"source"`
}

// CreateTaskWithSource
//
//	INSERT INTO tasks (job_id, name, commands, env, requires, timeout_seconds, retries, source)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
//	RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
func (q *Queries) CreateTaskWithSource(ctx context.Context, arg CreateTaskWithSourceParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTaskWithSource,
		arg.JobID,
		arg.Name,
		arg.Commands,
		arg.Env,
		arg.Requires,
		arg.TimeoutSeconds,
		arg.Retries,
		arg.Source,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}

const failDependentTasks = `-- name: FailDependentTasks :exec
WITH RECURSIVE blocked AS (
    SELECT task_id FROM task_dependencies WHERE depends_on_task_id = $1::uuid
    UNION ALL
    SELECT td.task_id FROM task_dependencies td
    JOIN blocked b ON td.depends_on_task_id = b.task_id
)
UPDATE tasks
SET status = 'failed', finished_at = NOW()
WHERE status = 'pending'
  AND id IN (SELECT task_id FROM blocked)
`

// Mark all tasks that transitively depend on a failed task as failed.
// Uses a recursive CTE to walk the full dependency chain.
// Call this after marking a task as failed.
//
//	WITH RECURSIVE blocked AS (
//	    SELECT task_id FROM task_dependencies WHERE depends_on_task_id = $1::uuid
//	    UNION ALL
//	    SELECT td.task_id FROM task_dependencies td
//	    JOIN blocked b ON td.depends_on_task_id = b.task_id
//	)
//	UPDATE tasks
//	SET status = 'failed', finished_at = NOW()
//	WHERE status = 'pending'
//	  AND id IN (SELECT task_id FROM blocked)
func (q *Queries) FailDependentTasks(ctx context.Context, failedTaskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, failDependentTasks, failedTaskID)
	return err
}

const getActiveTasksForWorker = `-- name: GetActiveTasksForWorker :many
SELECT id, assignment_epoch
FROM tasks
WHERE worker_id = $1 AND status IN ('dispatched', 'running')
ORDER BY id
`

type GetActiveTasksForWorkerRow struct {
	ID              pgtype.UUID `json:"id"`
	AssignmentEpoch int32       `json:"assignment_epoch"`
}

// Returns all non-terminal tasks currently assigned to a given worker.
// Used at reconcile time to compare server's view with the agent's
// running_tasks report.
//
//	SELECT id, assignment_epoch
//	FROM tasks
//	WHERE worker_id = $1 AND status IN ('dispatched', 'running')
//	ORDER BY id
func (q *Queries) GetActiveTasksForWorker(ctx context.Context, workerID pgtype.UUID) ([]GetActiveTasksForWorkerRow, error) {
	rows, err := q.db.Query(ctx, getActiveTasksForWorker, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveTasksForWorkerRow
	for rows.Next() {
		var i GetActiveTasksForWorkerRow
		if err := rows.Scan(&i.ID, &i.AssignmentEpoch); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEligibleTasks = `-- name: GetEligibleTasks :many
SELECT t.id, t.job_id, t.name, t.env, t.requires, t.timeout_seconds, t.retries, t.retry_count, t.status, t.worker_id, t.started_at, t.finished_at, t.created_at, t.assignment_epoch, t.source, t.commands FROM tasks t
WHERE t.status = 'pending'
  AND NOT EXISTS (
    SELECT 1 FROM task_dependencies td
    JOIN tasks dep ON dep.id = td.depends_on_task_id
    WHERE td.task_id = t.id
      AND dep.status != 'done'
  )
ORDER BY t.created_at
`

// Tasks that are pending and have no unfinished dependencies.
//
//	SELECT t.id, t.job_id, t.name, t.env, t.requires, t.timeout_seconds, t.retries, t.retry_count, t.status, t.worker_id, t.started_at, t.finished_at, t.created_at, t.assignment_epoch, t.source, t.commands FROM tasks t
//	WHERE t.status = 'pending'
//	  AND NOT EXISTS (
//	    SELECT 1 FROM task_dependencies td
//	    JOIN tasks dep ON dep.id = td.depends_on_task_id
//	    WHERE td.task_id = t.id
//	      AND dep.status != 'done'
//	  )
//	ORDER BY t.created_at
func (q *Queries) GetEligibleTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, getEligibleTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.Env,
			&i.Requires,
			&i.TimeoutSeconds,
			&i.Retries,
			&i.RetryCount,
			&i.Status,
			&i.WorkerID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.AssignmentEpoch,
			&i.Source,
			&i.Commands,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands FROM tasks WHERE id = $1
`

// GetTask
//
//	SELECT id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands FROM tasks WHERE id = $1
func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}

const getTaskDependencies = `-- name: GetTaskDependencies :many
SELECT depends_on_task_id FROM task_dependencies WHERE task_id = $1
`

// GetTaskDependencies
//
//	SELECT depends_on_task_id FROM task_dependencies WHERE task_id = $1
func (q *Queries) GetTaskDependencies(ctx context.Context, taskID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getTaskDependencies, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var depends_on_task_id pgtype.UUID
		if err := rows.Scan(&depends_on_task_id); err != nil {
			return nil, err
		}
		items = append(items, depends_on_task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskLogs = `-- name: GetTaskLogs :many
SELECT id, task_id, stream, content, created_at FROM task_logs WHERE task_id = $1 ORDER BY id
`

// GetTaskLogs
//
//	SELECT id, task_id, stream, content, created_at FROM task_logs WHERE task_id = $1 ORDER BY id
func (q *Queries) GetTaskLogs(ctx context.Context, taskID pgtype.UUID) ([]TaskLog, error) {
	rows, err := q.db.Query(ctx, getTaskLogs, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskLog
	for rows.Next() {
		var i TaskLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Stream,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementTaskRetryCount = `-- name: IncrementTaskRetryCount :one
UPDATE tasks
SET retry_count = retry_count + 1, status = 'pending', worker_id = NULL, started_at = NULL, finished_at = NULL
WHERE id = $1
RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
`

// IncrementTaskRetryCount
//
//	UPDATE tasks
//	SET retry_count = retry_count + 1, status = 'pending', worker_id = NULL, started_at = NULL, finished_at = NULL
//	WHERE id = $1
//	RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
func (q *Queries) IncrementTaskRetryCount(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, incrementTaskRetryCount, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}

const listGraceCandidates = `-- name: ListGraceCandidates :many
SELECT DISTINCT w.id, w.disconnected_at
FROM workers w
JOIN tasks t ON t.worker_id = w.id
WHERE t.status IN ('dispatched', 'running')
`

type ListGraceCandidatesRow struct {
	ID             pgtype.UUID        `json:"id"`
	DisconnectedAt pgtype.Timestamptz `json:"disconnected_at"`
}

// Returns id and disconnected_at for each worker that has at least one
// non-terminal task assigned. Used at server startup to seed grace timers
// with the correct remaining duration based on persisted disconnect time.
//
//	SELECT DISTINCT w.id, w.disconnected_at
//	FROM workers w
//	JOIN tasks t ON t.worker_id = w.id
//	WHERE t.status IN ('dispatched', 'running')
func (q *Queries) ListGraceCandidates(ctx context.Context) ([]ListGraceCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listGraceCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGraceCandidatesRow
	for rows.Next() {
		var i ListGraceCandidatesRow
		if err := rows.Scan(&i.ID, &i.DisconnectedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByJob = `-- name: ListTasksByJob :many
SELECT id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands FROM tasks WHERE job_id = $1 ORDER BY created_at
`

// ListTasksByJob
//
//	SELECT id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands FROM tasks WHERE job_id = $1 ORDER BY created_at
func (q *Queries) ListTasksByJob(ctx context.Context, jobID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.Env,
			&i.Requires,
			&i.TimeoutSeconds,
			&i.Retries,
			&i.RetryCount,
			&i.Status,
			&i.WorkerID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.AssignmentEpoch,
			&i.Source,
			&i.Commands,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyTaskCompleted = `-- name: NotifyTaskCompleted :exec
SELECT pg_notify('relay_task_completed', '')
`

// Wakes any LISTENers on relay_task_completed.
//
//	SELECT pg_notify('relay_task_completed', '')
func (q *Queries) NotifyTaskCompleted(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifyTaskCompleted)
	return err
}

const notifyTaskSubmitted = `-- name: NotifyTaskSubmitted :exec
SELECT pg_notify('relay_task_submitted', '')
`

// Wakes any LISTENers on relay_task_submitted. Payload is empty; listeners
// coalesce into a single dispatch trigger.
//
//	SELECT pg_notify('relay_task_submitted', '')
func (q *Queries) NotifyTaskSubmitted(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifyTaskSubmitted)
	return err
}

const requeueAllActiveTasks = `-- name: RequeueAllActiveTasks :exec
UPDATE tasks
SET status = 'pending', worker_id = NULL, started_at = NULL
WHERE status IN ('dispatched', 'running')
`

// Called on coordinator startup to recover from an unclean shutdown.
//
//	UPDATE tasks
//	SET status = 'pending', worker_id = NULL, started_at = NULL
//	WHERE status IN ('dispatched', 'running')
func (q *Queries) RequeueAllActiveTasks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, requeueAllActiveTasks)
	return err
}

const requeueTask = `-- name: RequeueTask :exec
UPDATE tasks
SET status = 'pending', worker_id = NULL, started_at = NULL
WHERE id = $1 AND status = 'dispatched'
`

// Revert a single task from 'dispatched' back to 'pending'.
// Used when the registry send fails after the task has been claimed.
//
//	UPDATE tasks
//	SET status = 'pending', worker_id = NULL, started_at = NULL
//	WHERE id = $1 AND status = 'dispatched'
func (q *Queries) RequeueTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, requeueTask, id)
	return err
}

const requeueTaskByID = `-- name: RequeueTaskByID :exec
UPDATE tasks
SET status = 'pending',
    worker_id = NULL,
    started_at = NULL,
    finished_at = NULL
WHERE id = $1 AND status IN ('dispatched', 'running')
`

// Revert a single task back to 'pending' regardless of current status.
// Used by the reconcile path when the coordinator has a task assigned
// that the agent didn't report as running.
//
//	UPDATE tasks
//	SET status = 'pending',
//	    worker_id = NULL,
//	    started_at = NULL,
//	    finished_at = NULL
//	WHERE id = $1 AND status IN ('dispatched', 'running')
func (q *Queries) RequeueTaskByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, requeueTaskByID, id)
	return err
}

const requeueWorkerTasks = `-- name: RequeueWorkerTasks :exec
UPDATE tasks
SET status = 'pending', worker_id = NULL, started_at = NULL
WHERE worker_id = $1 AND status IN ('dispatched', 'running')
`

// Re-queue dispatched/running tasks for a worker that has disconnected.
//
//	UPDATE tasks
//	SET status = 'pending', worker_id = NULL, started_at = NULL
//	WHERE worker_id = $1 AND status IN ('dispatched', 'running')
func (q *Queries) RequeueWorkerTasks(ctx context.Context, workerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, requeueWorkerTasks, workerID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2, worker_id = $3, started_at = $4, finished_at = $5
WHERE id = $1 AND assignment_epoch = $6
RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
`

type UpdateTaskStatusParams struct {
	ID              pgtype.UUID        `json:"id"`
	Status          string             `json:"status"`
	WorkerID        pgtype.UUID        `json:"worker_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	AssignmentEpoch int32              `json:"assignment_epoch"`
}

// Updates a task's status only if the caller's epoch matches the current
// assignment. Returns pgx.ErrNoRows if the caller's epoch is stale (zombie
// status update from a prior assignment).
//
//	UPDATE tasks
//	SET status = $2, worker_id = $3, started_at = $4, finished_at = $5
//	WHERE id = $1 AND assignment_epoch = $6
//	RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus,
		arg.ID,
		arg.Status,
		arg.WorkerID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.AssignmentEpoch,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}

const updateTaskStatusEpoch = `-- name: UpdateTaskStatusEpoch :one
UPDATE tasks
SET status = $1
WHERE id = $2 AND assignment_epoch = $3
RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
`

type UpdateTaskStatusEpochParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
	Epoch  int32       `json:"epoch"`
}

// Updates a task's status only if the caller's epoch matches the current
// assignment_epoch. Returns pgx.ErrNoRows if the epoch is stale.
//
//	UPDATE tasks
//	SET status = $1
//	WHERE id = $2 AND assignment_epoch = $3
//	RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
func (q *Queries) UpdateTaskStatusEpoch(ctx context.Context, arg UpdateTaskStatusEpochParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatusEpoch, arg.Status, arg.ID, arg.Epoch)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}
