// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendTaskLog = `-- name: AppendTaskLog :exec
INSERT INTO task_logs (task_id, stream, content) VALUES ($1, $2, $3)
`

type AppendTaskLogParams struct {
	TaskID  pgtype.UUID `json:"task_id"`
	Stream  string      `json:"stream"`
	Content string      `json:"content"`
}

// AppendTaskLog
//
//	INSERT INTO task_logs (task_id, stream, content) VALUES ($1, $2, $3)
func (q *Queries) AppendTaskLog(ctx context.Context, arg AppendTaskLogParams) error {
	_, err := q.db.Exec(ctx, appendTaskLog, arg.TaskID, arg.Stream, arg.Content)
	return err
}

const claimTaskForWorker = `-- name: ClaimTaskForWorker :one
UPDATE tasks
SET status = 'dispatched', worker_id = $2
WHERE id = $1 AND status = 'pending'
RETURNING id, job_id, name, command, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch
`

type ClaimTaskForWorkerParams struct {
	ID       pgtype.UUID `json:"id"`
	WorkerID pgtype.UUID `json:"worker_id"`
}

// Atomically transition a pending task to 'dispatched' on the given worker.
// Returns pgx.ErrNoRows if the task is no longer pending (another dispatcher
// already claimed it, or the row vanished). Eliminates double-dispatch.
//
//	UPDATE tasks
//	SET status = 'dispatched', worker_id = $2
//	WHERE id = $1 AND status = 'pending'
//	RETURNING id, job_id, name, command, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch
func (q *Queries) ClaimTaskForWorker(ctx context.Context, arg ClaimTaskForWorkerParams) (Task, error) {
	row := q.db.QueryRow(ctx, claimTaskForWorker, arg.ID, arg.WorkerID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Command,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
	)
	return i, err
}

const countActiveTasksForWorker = `-- name: CountActiveTasksForWorker :one
SELECT COUNT(*) FROM tasks
WHERE worker_id = $1 AND status IN ('dispatched', 'running')
`

// CountActiveTasksForWorker
//
//	SELECT COUNT(*) FROM tasks
//	WHERE worker_id = $1 AND status IN ('dispatched', 'running')
func (q *Queries) CountActiveTasksForWorker(ctx context.Context, workerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTasksForWorker, workerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (job_id, name, command, env, requires, timeout_seconds, retries)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, name, command, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch
`

type CreateTaskParams struct {
	JobID          pgtype.UUID `json:"job_id"`
	Name           string      `json:"name"`
	Command        []string    `json:"command"`
	Env            []byte      `json:"env"`
	Requires       []byte      `json:"requires"`
	TimeoutSeconds *int32      `json:"timeout_seconds"`
	Retries        int32       `json:"retries"`
}

// CreateTask
//
//	INSERT INTO tasks (job_id, name, command, env, requires, timeout_seconds, retries)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, job_id, name, command, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.JobID,
		arg.Name,
		arg.Command,
		arg.Env,
		arg.Requires,
		arg.TimeoutSeconds,
		arg.Retries,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Command,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
	)
	return i, err
}

const createTaskDependency = `-- name: CreateTaskDependency :exec
INSERT INTO task_dependencies (task_id, depends_on_task_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateTaskDependencyParams struct {
	TaskID          pgtype.UUID `json:"task_id"`
	DependsOnTaskID pgtype.UUID `json:"depends_on_task_id"`
}

// CreateTaskDependency
//
//	INSERT INTO task_dependencies (task_id, depends_on_task_id)
//	VALUES ($1, $2)
//	ON CONFLICT DO NOTHING
func (q *Queries) CreateTaskDependency(ctx context.Context, arg CreateTaskDependencyParams) error {
	_, err := q.db.Exec(ctx, createTaskDependency, arg.TaskID, arg.DependsOnTaskID)
	return err
}

const failDependentTasks = `-- name: FailDependentTasks :exec
WITH RECURSIVE blocked AS (
    SELECT task_id FROM task_dependencies WHERE depends_on_task_id = $1::uuid
    UNION ALL
    SELECT td.task_id FROM task_dependencies td
    JOIN blocked b ON td.depends_on_task_id = b.task_id
)
UPDATE tasks
SET status = 'failed', finished_at = NOW()
WHERE status = 'pending'
  AND id IN (SELECT task_id FROM blocked)
`

// Mark all tasks that transitively depend on a failed task as failed.
// Uses a recursive CTE to walk the full dependency chain.
// Call this after marking a task as failed.
//
//	WITH RECURSIVE blocked AS (
//	    SELECT task_id FROM task_dependencies WHERE depends_on_task_id = $1::uuid
//	    UNION ALL
//	    SELECT td.task_id FROM task_dependencies td
//	    JOIN blocked b ON td.depends_on_task_id = b.task_id
//	)
//	UPDATE tasks
//	SET status = 'failed', finished_at = NOW()
//	WHERE status = 'pending'
//	  AND id IN (SELECT task_id FROM blocked)
func (q *Queries) FailDependentTasks(ctx context.Context, failedTaskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, failDependentTasks, failedTaskID)
	return err
}

const getEligibleTasks = `-- name: GetEligibleTasks :many
SELECT t.id, t.job_id, t.name, t.command, t.env, t.requires, t.timeout_seconds, t.retries, t.retry_count, t.status, t.worker_id, t.started_at, t.finished_at, t.created_at, t.assignment_epoch FROM tasks t
WHERE t.status = 'pending'
  AND NOT EXISTS (
    SELECT 1 FROM task_dependencies td
    JOIN tasks dep ON dep.id = td.depends_on_task_id
    WHERE td.task_id = t.id
      AND dep.status != 'done'
  )
ORDER BY t.created_at
`

// Tasks that are pending and have no unfinished dependencies.
//
//	SELECT t.id, t.job_id, t.name, t.command, t.env, t.requires, t.timeout_seconds, t.retries, t.retry_count, t.status, t.worker_id, t.started_at, t.finished_at, t.created_at, t.assignment_epoch FROM tasks t
//	WHERE t.status = 'pending'
//	  AND NOT EXISTS (
//	    SELECT 1 FROM task_dependencies td
//	    JOIN tasks dep ON dep.id = td.depends_on_task_id
//	    WHERE td.task_id = t.id
//	      AND dep.status != 'done'
//	  )
//	ORDER BY t.created_at
func (q *Queries) GetEligibleTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, getEligibleTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.Command,
			&i.Env,
			&i.Requires,
			&i.TimeoutSeconds,
			&i.Retries,
			&i.RetryCount,
			&i.Status,
			&i.WorkerID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.AssignmentEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, job_id, name, command, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch FROM tasks WHERE id = $1
`

// GetTask
//
//	SELECT id, job_id, name, command, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch FROM tasks WHERE id = $1
func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Command,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
	)
	return i, err
}

const getTaskDependencies = `-- name: GetTaskDependencies :many
SELECT depends_on_task_id FROM task_dependencies WHERE task_id = $1
`

// GetTaskDependencies
//
//	SELECT depends_on_task_id FROM task_dependencies WHERE task_id = $1
func (q *Queries) GetTaskDependencies(ctx context.Context, taskID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getTaskDependencies, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var depends_on_task_id pgtype.UUID
		if err := rows.Scan(&depends_on_task_id); err != nil {
			return nil, err
		}
		items = append(items, depends_on_task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskLogs = `-- name: GetTaskLogs :many
SELECT id, task_id, stream, content, created_at FROM task_logs WHERE task_id = $1 ORDER BY id
`

// GetTaskLogs
//
//	SELECT id, task_id, stream, content, created_at FROM task_logs WHERE task_id = $1 ORDER BY id
func (q *Queries) GetTaskLogs(ctx context.Context, taskID pgtype.UUID) ([]TaskLog, error) {
	rows, err := q.db.Query(ctx, getTaskLogs, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskLog
	for rows.Next() {
		var i TaskLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Stream,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementTaskRetryCount = `-- name: IncrementTaskRetryCount :one
UPDATE tasks
SET retry_count = retry_count + 1, status = 'pending', worker_id = NULL, started_at = NULL, finished_at = NULL
WHERE id = $1
RETURNING id, job_id, name, command, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch
`

// IncrementTaskRetryCount
//
//	UPDATE tasks
//	SET retry_count = retry_count + 1, status = 'pending', worker_id = NULL, started_at = NULL, finished_at = NULL
//	WHERE id = $1
//	RETURNING id, job_id, name, command, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch
func (q *Queries) IncrementTaskRetryCount(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, incrementTaskRetryCount, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Command,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
	)
	return i, err
}

const listTasksByJob = `-- name: ListTasksByJob :many
SELECT id, job_id, name, command, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch FROM tasks WHERE job_id = $1 ORDER BY created_at
`

// ListTasksByJob
//
//	SELECT id, job_id, name, command, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch FROM tasks WHERE job_id = $1 ORDER BY created_at
func (q *Queries) ListTasksByJob(ctx context.Context, jobID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.Command,
			&i.Env,
			&i.Requires,
			&i.TimeoutSeconds,
			&i.Retries,
			&i.RetryCount,
			&i.Status,
			&i.WorkerID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.AssignmentEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueAllActiveTasks = `-- name: RequeueAllActiveTasks :exec
UPDATE tasks
SET status = 'pending', worker_id = NULL, started_at = NULL
WHERE status IN ('dispatched', 'running')
`

// Called on coordinator startup to recover from an unclean shutdown.
//
//	UPDATE tasks
//	SET status = 'pending', worker_id = NULL, started_at = NULL
//	WHERE status IN ('dispatched', 'running')
func (q *Queries) RequeueAllActiveTasks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, requeueAllActiveTasks)
	return err
}

const requeueTask = `-- name: RequeueTask :exec
UPDATE tasks
SET status = 'pending', worker_id = NULL, started_at = NULL
WHERE id = $1 AND status = 'dispatched'
`

// Revert a single task from 'dispatched' back to 'pending'.
// Used when the registry send fails after the task has been claimed.
//
//	UPDATE tasks
//	SET status = 'pending', worker_id = NULL, started_at = NULL
//	WHERE id = $1 AND status = 'dispatched'
func (q *Queries) RequeueTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, requeueTask, id)
	return err
}

const requeueWorkerTasks = `-- name: RequeueWorkerTasks :exec
UPDATE tasks
SET status = 'pending', worker_id = NULL, started_at = NULL
WHERE worker_id = $1 AND status IN ('dispatched', 'running')
`

// Re-queue dispatched/running tasks for a worker that has disconnected.
//
//	UPDATE tasks
//	SET status = 'pending', worker_id = NULL, started_at = NULL
//	WHERE worker_id = $1 AND status IN ('dispatched', 'running')
func (q *Queries) RequeueWorkerTasks(ctx context.Context, workerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, requeueWorkerTasks, workerID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2, worker_id = $3, started_at = $4, finished_at = $5
WHERE id = $1
RETURNING id, job_id, name, command, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch
`

type UpdateTaskStatusParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	WorkerID   pgtype.UUID        `json:"worker_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

// UpdateTaskStatus
//
//	UPDATE tasks
//	SET status = $2, worker_id = $3, started_at = $4, finished_at = $5
//	WHERE id = $1
//	RETURNING id, job_id, name, command, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch
func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus,
		arg.ID,
		arg.Status,
		arg.WorkerID,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Command,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
	)
	return i, err
}
