// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendTaskLog = `-- name: AppendTaskLog :one
WITH fence AS (
    SELECT t.job_id FROM tasks t
    WHERE t.id = $1
      AND t.assignment_epoch = $2
      AND t.worker_id = $3
), ins AS (
    INSERT INTO task_logs (task_id, stream, content)
    SELECT $1, $4, $5 FROM fence
    RETURNING id, created_at
)
SELECT ins.id, ins.created_at, fence.job_id FROM ins, fence
`

type AppendTaskLogParams struct {
	TaskID          pgtype.UUID `json:"task_id"`
	AssignmentEpoch int32       `json:"assignment_epoch"`
	WorkerID        pgtype.UUID `json:"worker_id"`
	Stream          string      `json:"stream"`
	Content         string      `json:"content"`
}

type AppendTaskLogRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	JobID     pgtype.UUID        `json:"job_id"`
}

// Inserts a log chunk only if BOTH fence predicates hold: the task is currently
// assigned to the sending worker (identity), and the caller's epoch matches the
// task's current assignment (currency). The epoch answers "is this generation
// current"; the worker id answers "are you who you say you are". Neither
// substitutes for the other, and neither is redundant - do not delete either.
// Returns the inserted row's id (the seq the polling endpoint pages by) plus
// created_at plus the task's job_id - all from one round trip, because this runs
// synchronously on the agent's gRPC recv goroutine and a second query here would
// delay that worker's status and telemetry ingest too.
// A chunk failing EITHER predicate - a stale chunk from a reassigned or
// cancelled generation, or a chunk from an agent that is not this task's
// assignee - matches no fence row, inserts nothing, and returns zero rows ->
// pgx.ErrNoRows. Callers must treat ErrNoRows as "one or both checks failed:
// drop silently, do not publish" and any other error as a real failure worth
// logging. The two cases are deliberately indistinguishable here; see the spec.
// The worker_id comparison must stay a plain `=`. tasks.worker_id is NULLABLE,
// so `=` makes a never-claimed task (worker_id NULL) reject every append, which
// is exactly the hole this predicate closes, and makes a caller that lost its
// own identity (a zero-value pgtype.UUID binds SQL NULL) fail closed. Rewriting
// it as `IS NOT DISTINCT FROM` would let a NULL parameter match a NULL
// worker_id and re-open that hole. Do not "fix the NULL bug" here.
// The tasks alias and the qualified column references are load-bearing: without
// them sqlc's analyzer cannot resolve "id" across the two CTEs and fails with
// 'column reference "id" is ambiguous'. Only job_id is selected because that is
// all the publish needs; the fence's job is to yield exactly one row, or none.
//
//	WITH fence AS (
//	    SELECT t.job_id FROM tasks t
//	    WHERE t.id = $1
//	      AND t.assignment_epoch = $2
//	      AND t.worker_id = $3
//	), ins AS (
//	    INSERT INTO task_logs (task_id, stream, content)
//	    SELECT $1, $4, $5 FROM fence
//	    RETURNING id, created_at
//	)
//	SELECT ins.id, ins.created_at, fence.job_id FROM ins, fence
func (q *Queries) AppendTaskLog(ctx context.Context, arg AppendTaskLogParams) (AppendTaskLogRow, error) {
	row := q.db.QueryRow(ctx, appendTaskLog,
		arg.TaskID,
		arg.AssignmentEpoch,
		arg.WorkerID,
		arg.Stream,
		arg.Content,
	)
	var i AppendTaskLogRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.JobID)
	return i, err
}

const cancelJobTasks = `-- name: CancelJobTasks :exec
UPDATE tasks
SET status = 'failed',
    worker_id = NULL,
    finished_at = NOW(),
    assignment_epoch = assignment_epoch + 1
WHERE job_id = $1 AND status IN ('pending', 'queued', 'running', 'dispatched')
`

// Mark every non-terminal task of a job as failed when the job is cancelled.
// Bumps assignment_epoch so any in-flight status update or log chunk from the
// assigned agent is rejected by the epoch fence. Unlike UpdateTaskStatus this
// does not fence on the caller's epoch: the cancel handler does not track each
// task's current generation, and cancellation ends the assignment regardless.
//
//	UPDATE tasks
//	SET status = 'failed',
//	    worker_id = NULL,
//	    finished_at = NOW(),
//	    assignment_epoch = assignment_epoch + 1
//	WHERE job_id = $1 AND status IN ('pending', 'queued', 'running', 'dispatched')
func (q *Queries) CancelJobTasks(ctx context.Context, jobID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelJobTasks, jobID)
	return err
}

const claimTaskForWorker = `-- name: ClaimTaskForWorker :one
UPDATE tasks
SET status = 'dispatched',
    worker_id = $2,
    assignment_epoch = assignment_epoch + 1
WHERE id = $1 AND status = 'pending'
RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
`

type ClaimTaskForWorkerParams struct {
	ID       pgtype.UUID `json:"id"`
	WorkerID pgtype.UUID `json:"worker_id"`
}

// Atomically transition a pending task to 'dispatched' on the given worker.
// Increments assignment_epoch so subsequent status updates from prior
// generations can be rejected. Returns pgx.ErrNoRows if the task is no longer
// pending (another dispatcher already claimed it, or the row vanished).
//
//	UPDATE tasks
//	SET status = 'dispatched',
//	    worker_id = $2,
//	    assignment_epoch = assignment_epoch + 1
//	WHERE id = $1 AND status = 'pending'
//	RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
func (q *Queries) ClaimTaskForWorker(ctx context.Context, arg ClaimTaskForWorkerParams) (Task, error) {
	row := q.db.QueryRow(ctx, claimTaskForWorker, arg.ID, arg.WorkerID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}

const countActiveTasksByAllWorkers = `-- name: CountActiveTasksByAllWorkers :many
SELECT worker_id, count(*)::bigint AS active
FROM tasks
WHERE worker_id IS NOT NULL
  AND status IN ('dispatched', 'running')
GROUP BY worker_id
`

type CountActiveTasksByAllWorkersRow struct {
	WorkerID pgtype.UUID `json:"worker_id"`
	Active   int64       `json:"active"`
}

// Per-worker count of non-terminal tasks. Used by the dispatcher to compute
// available slots in one query rather than N per cycle.
//
//	SELECT worker_id, count(*)::bigint AS active
//	FROM tasks
//	WHERE worker_id IS NOT NULL
//	  AND status IN ('dispatched', 'running')
//	GROUP BY worker_id
func (q *Queries) CountActiveTasksByAllWorkers(ctx context.Context) ([]CountActiveTasksByAllWorkersRow, error) {
	rows, err := q.db.Query(ctx, countActiveTasksByAllWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountActiveTasksByAllWorkersRow
	for rows.Next() {
		var i CountActiveTasksByAllWorkersRow
		if err := rows.Scan(&i.WorkerID, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTaskLogs = `-- name: CountTaskLogs :one
SELECT COUNT(*) FROM task_logs WHERE task_id = $1
`

// CountTaskLogs
//
//	SELECT COUNT(*) FROM task_logs WHERE task_id = $1
func (q *Queries) CountTaskLogs(ctx context.Context, taskID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTaskLogs, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (job_id, name, commands, env, requires, timeout_seconds, retries)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
`

type CreateTaskParams struct {
	JobID          pgtype.UUID `json:"job_id"`
	Name           string      `json:"name"`
	Commands       []byte      `json:"commands"`
	Env            []byte      `json:"env"`
	Requires       []byte      `json:"requires"`
	TimeoutSeconds *int32      `json:"timeout_seconds"`
	Retries        int32       `json:"retries"`
}

// CreateTask
//
//	INSERT INTO tasks (job_id, name, commands, env, requires, timeout_seconds, retries)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.JobID,
		arg.Name,
		arg.Commands,
		arg.Env,
		arg.Requires,
		arg.TimeoutSeconds,
		arg.Retries,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}

const createTaskDependency = `-- name: CreateTaskDependency :exec
INSERT INTO task_dependencies (task_id, depends_on_task_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateTaskDependencyParams struct {
	TaskID          pgtype.UUID `json:"task_id"`
	DependsOnTaskID pgtype.UUID `json:"depends_on_task_id"`
}

// CreateTaskDependency
//
//	INSERT INTO task_dependencies (task_id, depends_on_task_id)
//	VALUES ($1, $2)
//	ON CONFLICT DO NOTHING
func (q *Queries) CreateTaskDependency(ctx context.Context, arg CreateTaskDependencyParams) error {
	_, err := q.db.Exec(ctx, createTaskDependency, arg.TaskID, arg.DependsOnTaskID)
	return err
}

const createTaskWithSource = `-- name: CreateTaskWithSource :one
INSERT INTO tasks (job_id, name, commands, env, requires, timeout_seconds, retries, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
`

type CreateTaskWithSourceParams struct {
	JobID          pgtype.UUID `json:"job_id"`
	Name           string      `json:"name"`
	Commands       []byte      `json:"commands"`
	Env            []byte      `json:"env"`
	Requires       []byte      `json:"requires"`
	TimeoutSeconds *int32      `json:"timeout_seconds"`
	Retries        int32       `json:"retries"`
	Source         []byte      `json:"source"`
}

// CreateTaskWithSource
//
//	INSERT INTO tasks (job_id, name, commands, env, requires, timeout_seconds, retries, source)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
//	RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
func (q *Queries) CreateTaskWithSource(ctx context.Context, arg CreateTaskWithSourceParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTaskWithSource,
		arg.JobID,
		arg.Name,
		arg.Commands,
		arg.Env,
		arg.Requires,
		arg.TimeoutSeconds,
		arg.Retries,
		arg.Source,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}

const failDependentTasks = `-- name: FailDependentTasks :exec
WITH RECURSIVE blocked AS (
    SELECT task_id FROM task_dependencies WHERE depends_on_task_id = $1::uuid
    UNION
    SELECT td.task_id FROM task_dependencies td
    JOIN blocked b ON td.depends_on_task_id = b.task_id
)
UPDATE tasks
SET status = 'failed', finished_at = NOW()
WHERE status = 'pending'
  AND id IN (SELECT task_id FROM blocked)
`

// Mark all tasks that transitively depend on a failed task as failed.
// Uses a recursive CTE to walk the full dependency chain.
// Call this after marking a task as failed.
//
//	WITH RECURSIVE blocked AS (
//	    SELECT task_id FROM task_dependencies WHERE depends_on_task_id = $1::uuid
//	    UNION
//	    SELECT td.task_id FROM task_dependencies td
//	    JOIN blocked b ON td.depends_on_task_id = b.task_id
//	)
//	UPDATE tasks
//	SET status = 'failed', finished_at = NOW()
//	WHERE status = 'pending'
//	  AND id IN (SELECT task_id FROM blocked)
func (q *Queries) FailDependentTasks(ctx context.Context, failedTaskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, failDependentTasks, failedTaskID)
	return err
}

const getActiveTasksForWorker = `-- name: GetActiveTasksForWorker :many
SELECT id, assignment_epoch
FROM tasks
WHERE worker_id = $1 AND status IN ('dispatched', 'running')
ORDER BY id
`

type GetActiveTasksForWorkerRow struct {
	ID              pgtype.UUID `json:"id"`
	AssignmentEpoch int32       `json:"assignment_epoch"`
}

// Returns all non-terminal tasks currently assigned to a given worker.
// Used at reconcile time to compare server's view with the agent's
// running_tasks report.
//
//	SELECT id, assignment_epoch
//	FROM tasks
//	WHERE worker_id = $1 AND status IN ('dispatched', 'running')
//	ORDER BY id
func (q *Queries) GetActiveTasksForWorker(ctx context.Context, workerID pgtype.UUID) ([]GetActiveTasksForWorkerRow, error) {
	rows, err := q.db.Query(ctx, getActiveTasksForWorker, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveTasksForWorkerRow
	for rows.Next() {
		var i GetActiveTasksForWorkerRow
		if err := rows.Scan(&i.ID, &i.AssignmentEpoch); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEligibleTasks = `-- name: GetEligibleTasks :many
SELECT t.id, t.job_id, t.name, t.env, t.requires, t.timeout_seconds, t.retries, t.retry_count, t.status, t.worker_id, t.started_at, t.finished_at, t.created_at, t.assignment_epoch, t.source, t.commands FROM tasks t
WHERE t.status = 'pending'
  AND NOT EXISTS (
    SELECT 1 FROM task_dependencies td
    JOIN tasks dep ON dep.id = td.depends_on_task_id
    WHERE td.task_id = t.id
      AND dep.status != 'done'
  )
ORDER BY t.created_at
`

// Tasks that are pending and have no unfinished dependencies.
//
//	SELECT t.id, t.job_id, t.name, t.env, t.requires, t.timeout_seconds, t.retries, t.retry_count, t.status, t.worker_id, t.started_at, t.finished_at, t.created_at, t.assignment_epoch, t.source, t.commands FROM tasks t
//	WHERE t.status = 'pending'
//	  AND NOT EXISTS (
//	    SELECT 1 FROM task_dependencies td
//	    JOIN tasks dep ON dep.id = td.depends_on_task_id
//	    WHERE td.task_id = t.id
//	      AND dep.status != 'done'
//	  )
//	ORDER BY t.created_at
func (q *Queries) GetEligibleTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, getEligibleTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.Env,
			&i.Requires,
			&i.TimeoutSeconds,
			&i.Retries,
			&i.RetryCount,
			&i.Status,
			&i.WorkerID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.AssignmentEpoch,
			&i.Source,
			&i.Commands,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands FROM tasks WHERE id = $1
`

// GetTask
//
//	SELECT id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands FROM tasks WHERE id = $1
func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}

const getTaskDependencies = `-- name: GetTaskDependencies :many
SELECT depends_on_task_id FROM task_dependencies WHERE task_id = $1
`

// GetTaskDependencies
//
//	SELECT depends_on_task_id FROM task_dependencies WHERE task_id = $1
func (q *Queries) GetTaskDependencies(ctx context.Context, taskID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getTaskDependencies, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var depends_on_task_id pgtype.UUID
		if err := rows.Scan(&depends_on_task_id); err != nil {
			return nil, err
		}
		items = append(items, depends_on_task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskLogs = `-- name: GetTaskLogs :many
SELECT id, task_id, stream, content, created_at FROM task_logs WHERE task_id = $1 ORDER BY id
`

// GetTaskLogs
//
//	SELECT id, task_id, stream, content, created_at FROM task_logs WHERE task_id = $1 ORDER BY id
func (q *Queries) GetTaskLogs(ctx context.Context, taskID pgtype.UUID) ([]TaskLog, error) {
	rows, err := q.db.Query(ctx, getTaskLogs, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskLog
	for rows.Next() {
		var i TaskLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Stream,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskLogsPage = `-- name: GetTaskLogsPage :many
SELECT id, task_id, stream, content, created_at
FROM task_logs
WHERE task_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type GetTaskLogsPageParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	ID     int64       `json:"id"`
	Limit  int32       `json:"limit"`
}

// Returns up to $3 log rows for the task with id > $2, ordered ascending.
//
//	SELECT id, task_id, stream, content, created_at
//	FROM task_logs
//	WHERE task_id = $1 AND id > $2
//	ORDER BY id
//	LIMIT $3
func (q *Queries) GetTaskLogsPage(ctx context.Context, arg GetTaskLogsPageParams) ([]TaskLog, error) {
	rows, err := q.db.Query(ctx, getTaskLogsPage, arg.TaskID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskLog
	for rows.Next() {
		var i TaskLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Stream,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementTaskRetryCount = `-- name: IncrementTaskRetryCount :one
UPDATE tasks
SET retry_count = retry_count + 1, status = 'pending', worker_id = NULL, started_at = NULL, finished_at = NULL,
    assignment_epoch = assignment_epoch + 1
WHERE id = $1
RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
`

// IncrementTaskRetryCount
//
//	UPDATE tasks
//	SET retry_count = retry_count + 1, status = 'pending', worker_id = NULL, started_at = NULL, finished_at = NULL,
//	    assignment_epoch = assignment_epoch + 1
//	WHERE id = $1
//	RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
func (q *Queries) IncrementTaskRetryCount(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, incrementTaskRetryCount, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}

const listGraceCandidates = `-- name: ListGraceCandidates :many
SELECT DISTINCT w.id, w.disconnected_at, w.connection_epoch
FROM workers w
JOIN tasks t ON t.worker_id = w.id
WHERE t.status IN ('dispatched', 'running')
`

type ListGraceCandidatesRow struct {
	ID              pgtype.UUID        `json:"id"`
	DisconnectedAt  pgtype.Timestamptz `json:"disconnected_at"`
	ConnectionEpoch int32              `json:"connection_epoch"`
}

// Returns id and disconnected_at for each worker that has at least one
// non-terminal task assigned. Used at server startup to seed grace timers
// with the correct remaining duration based on persisted disconnect time.
//
//	SELECT DISTINCT w.id, w.disconnected_at, w.connection_epoch
//	FROM workers w
//	JOIN tasks t ON t.worker_id = w.id
//	WHERE t.status IN ('dispatched', 'running')
func (q *Queries) ListGraceCandidates(ctx context.Context) ([]ListGraceCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listGraceCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGraceCandidatesRow
	for rows.Next() {
		var i ListGraceCandidatesRow
		if err := rows.Scan(&i.ID, &i.DisconnectedAt, &i.ConnectionEpoch); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByJob = `-- name: ListTasksByJob :many
SELECT id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands FROM tasks WHERE job_id = $1 ORDER BY created_at
`

// ListTasksByJob
//
//	SELECT id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands FROM tasks WHERE job_id = $1 ORDER BY created_at
func (q *Queries) ListTasksByJob(ctx context.Context, jobID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.Env,
			&i.Requires,
			&i.TimeoutSeconds,
			&i.Retries,
			&i.RetryCount,
			&i.Status,
			&i.WorkerID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.AssignmentEpoch,
			&i.Source,
			&i.Commands,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyTaskCompleted = `-- name: NotifyTaskCompleted :exec
SELECT pg_notify('relay_task_completed', '')
`

// Wakes any LISTENers on relay_task_completed.
//
//	SELECT pg_notify('relay_task_completed', '')
func (q *Queries) NotifyTaskCompleted(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifyTaskCompleted)
	return err
}

const notifyTaskSubmitted = `-- name: NotifyTaskSubmitted :exec
SELECT pg_notify('relay_task_submitted', '')
`

// Wakes any LISTENers on relay_task_submitted. Payload is empty; listeners
// coalesce into a single dispatch trigger.
//
//	SELECT pg_notify('relay_task_submitted', '')
func (q *Queries) NotifyTaskSubmitted(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifyTaskSubmitted)
	return err
}

const requeueTask = `-- name: RequeueTask :exec
UPDATE tasks
SET status = 'pending', worker_id = NULL, started_at = NULL,
    assignment_epoch = assignment_epoch + 1
WHERE id = $1 AND status = 'dispatched'
`

// Revert a single task from 'dispatched' back to 'pending'.
// Used when the registry send fails after the task has been claimed.
// Bumps assignment_epoch so a late update from the prior assignment is fenced out.
//
//	UPDATE tasks
//	SET status = 'pending', worker_id = NULL, started_at = NULL,
//	    assignment_epoch = assignment_epoch + 1
//	WHERE id = $1 AND status = 'dispatched'
func (q *Queries) RequeueTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, requeueTask, id)
	return err
}

const requeueTaskByID = `-- name: RequeueTaskByID :exec
UPDATE tasks
SET status = 'pending',
    worker_id = NULL,
    started_at = NULL,
    finished_at = NULL,
    assignment_epoch = assignment_epoch + 1
WHERE id = $1 AND status IN ('dispatched', 'running')
`

// Revert a single task back to 'pending' regardless of current status.
// Used by the reconcile path when the coordinator has a task assigned
// that the agent didn't report as running.
// Bumps assignment_epoch so a late update from the prior assignment is fenced out.
//
//	UPDATE tasks
//	SET status = 'pending',
//	    worker_id = NULL,
//	    started_at = NULL,
//	    finished_at = NULL,
//	    assignment_epoch = assignment_epoch + 1
//	WHERE id = $1 AND status IN ('dispatched', 'running')
func (q *Queries) RequeueTaskByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, requeueTaskByID, id)
	return err
}

const requeueWorkerTasks = `-- name: RequeueWorkerTasks :many
UPDATE tasks
SET status = 'pending',
    worker_id = NULL,
    started_at = NULL,
    assignment_epoch = assignment_epoch + 1
WHERE worker_id = $1 AND status IN ('dispatched', 'running')
RETURNING id
`

// Re-queue dispatched/running tasks for a worker that has disconnected or is
// being disabled. Bumps assignment_epoch so a stale status update or log chunk
// from the (possibly still-connected) agent is rejected by the epoch fence.
// Returns the affected task ids; the disable path uses them to send cancels,
// the disconnect/grace paths discard them.
//
//	UPDATE tasks
//	SET status = 'pending',
//	    worker_id = NULL,
//	    started_at = NULL,
//	    assignment_epoch = assignment_epoch + 1
//	WHERE worker_id = $1 AND status IN ('dispatched', 'running')
//	RETURNING id
func (q *Queries) RequeueWorkerTasks(ctx context.Context, workerID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, requeueWorkerTasks, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueWorkerTasksIfEpoch = `-- name: RequeueWorkerTasksIfEpoch :many
UPDATE tasks
SET status = 'pending',
    worker_id = NULL,
    started_at = NULL,
    assignment_epoch = assignment_epoch + 1
WHERE worker_id = $1 AND status IN ('dispatched', 'running')
  AND EXISTS (SELECT 1 FROM workers w WHERE w.id = $1 AND w.connection_epoch = $2)
RETURNING id
`

type RequeueWorkerTasksIfEpochParams struct {
	WorkerID        pgtype.UUID `json:"worker_id"`
	ConnectionEpoch int32       `json:"connection_epoch"`
}

// Re-queue dispatched/running tasks for a disconnected worker, but only if the
// worker's connection_epoch still matches the epoch the caller owned. If a fresh
// connection has superseded it, the EXISTS guard fails and zero tasks move.
// Bumps assignment_epoch on each requeued task (task-level fence preserved).
//
//	UPDATE tasks
//	SET status = 'pending',
//	    worker_id = NULL,
//	    started_at = NULL,
//	    assignment_epoch = assignment_epoch + 1
//	WHERE worker_id = $1 AND status IN ('dispatched', 'running')
//	  AND EXISTS (SELECT 1 FROM workers w WHERE w.id = $1 AND w.connection_epoch = $2)
//	RETURNING id
func (q *Queries) RequeueWorkerTasksIfEpoch(ctx context.Context, arg RequeueWorkerTasksIfEpochParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, requeueWorkerTasksIfEpoch, arg.WorkerID, arg.ConnectionEpoch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $1,
    started_at = $2,
    finished_at = $3
WHERE id = $4
  AND assignment_epoch = $5
  AND worker_id = $6
RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
`

type UpdateTaskStatusParams struct {
	Status          string             `json:"status"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	ID              pgtype.UUID        `json:"id"`
	AssignmentEpoch int32              `json:"assignment_epoch"`
	WorkerID        pgtype.UUID        `json:"worker_id"`
}

// Updates a task's status only if BOTH fence predicates hold: the task is
// currently assigned to the caller's worker (identity), and the caller's epoch
// matches the current assignment (currency). The epoch answers "is this
// generation current"; the worker id answers "are you who you say you are".
// Neither substitutes for the other - do not delete either.
// This statement no longer writes worker_id; the argument is a fence, not a
// value. That makes the old contract ("callers MUST pass the task's existing
// worker_id through, because clearing it would strand a live agent forever")
// structural rather than documented: the statement can no longer clear the
// column at all. It does not bump assignment_epoch either, so a terminal task
// keeps its assignee and trailing log chunks from the agent that just finished
// still pass AppendTaskLog's fence.
// The worker_id comparison must stay a plain `=`. tasks.worker_id is NULLABLE,
// so `=` makes a never-claimed task reject every update, which is the hole this
// predicate closes, and makes a caller that lost its identity (a zero-value
// pgtype.UUID binds SQL NULL) fail closed. `IS NOT DISTINCT FROM` would let a
// NULL parameter match a NULL worker_id and re-open it. Do not "fix the NULL
// bug" here.
// Both callers are fenced by the same statement deliberately;
// Dispatcher.failClaimedTask passes claimed.WorkerID from ClaimTaskForWorker,
// where the predicate is tautological by design. For why that beats a second
// un-fenced query or a "skip the check" sentinel, see
// docs/superpowers/specs/2026-08-12-taskstatus-update-assignee-fence.md.
// The fence binds a WORKER identity, not a connection: two concurrent streams
// registered for the same worker row both satisfy it. That matches AppendTaskLog
// and is what keeps reconnect-within-the-grace-window working, so it is not a
// regression - but do not read this predicate as connection-scoped.
// This predicate is NOT sufficient on its own: handleTaskStatus's retry branch
// calls IncrementTaskRetryCount (bare `WHERE id = $1`) and returns before ever
// reaching this statement, so the identity check also lives in Go, ahead of
// every side effect. Do not delete that one as redundant with this one.
//
//	UPDATE tasks
//	SET status = $1,
//	    started_at = $2,
//	    finished_at = $3
//	WHERE id = $4
//	  AND assignment_epoch = $5
//	  AND worker_id = $6
//	RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
		arg.AssignmentEpoch,
		arg.WorkerID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}

const updateTaskStatusEpoch = `-- name: UpdateTaskStatusEpoch :one
UPDATE tasks
SET status = $1
WHERE id = $2 AND assignment_epoch = $3
RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
`

type UpdateTaskStatusEpochParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
	Epoch  int32       `json:"epoch"`
}

// TEST-ONLY. No assignee fence - this is the one remaining writer to
// tasks.status that does not demand a worker id, so it fences currency without
// identity and a never-claimed task at epoch 0 accepts a write from anybody.
// Do NOT call this from production code: use UpdateTaskStatus, which fences on
// both. It has no production callers today and must not gain one.
// Updates a task's status only if the caller's epoch matches the current
// assignment_epoch. Returns pgx.ErrNoRows if the epoch is stale.
//
//	UPDATE tasks
//	SET status = $1
//	WHERE id = $2 AND assignment_epoch = $3
//	RETURNING id, job_id, name, env, requires, timeout_seconds, retries, retry_count, status, worker_id, started_at, finished_at, created_at, assignment_epoch, source, commands
func (q *Queries) UpdateTaskStatusEpoch(ctx context.Context, arg UpdateTaskStatusEpochParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatusEpoch, arg.Status, arg.ID, arg.Epoch)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Env,
		&i.Requires,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.RetryCount,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.AssignmentEpoch,
		&i.Source,
		&i.Commands,
	)
	return i, err
}
