// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveTokensForUser = `-- name: CountActiveTokensForUser :one
SELECT COUNT(*) FROM api_tokens
WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > NOW())
`

// The `total` for the sessions list, over the SAME predicate as the list
// statements, so the pagination footer cannot state a number the caller cannot
// page to.
//
// Same expiry predicate as ListActiveTokensForUserPage; see the note there.
//
//	SELECT COUNT(*) FROM api_tokens
//	WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > NOW())
func (q *Queries) CountActiveTokensForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTokensForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createToken = `-- name: CreateToken :one
INSERT INTO api_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, created_at, expires_at
`

type CreateTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// CreateToken
//
//	INSERT INTO api_tokens (user_id, token_hash, expires_at)
//	VALUES ($1, $2, $3)
//	RETURNING id, user_id, token_hash, created_at, expires_at
func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteOtherTokensForUser = `-- name: DeleteOtherTokensForUser :exec
DELETE FROM api_tokens WHERE user_id = $1 AND id <> $2
`

type DeleteOtherTokensForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

// DeleteOtherTokensForUser
//
//	DELETE FROM api_tokens WHERE user_id = $1 AND id <> $2
func (q *Queries) DeleteOtherTokensForUser(ctx context.Context, arg DeleteOtherTokensForUserParams) error {
	_, err := q.db.Exec(ctx, deleteOtherTokensForUser, arg.UserID, arg.ID)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM api_tokens WHERE id = $1 AND user_id = $2
`

type DeleteTokenParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Revoke ONE session, scoped to its owner.
//
// The user_id predicate is not redundant with the primary key. The id proves
// WHICH row, never WHOSE - the same distinction the epoch fence draws on tasks,
// where a matching epoch establishes currency but not identity (CLAUDE.md,
// "Invariants"). Both sibling deletes carry the predicate; this statement is the
// one whose id can plausibly arrive from the wire.
//
// The only caller today passes the token id BearerAuth resolved from the
// presented credential (internal/api/auth.go:341-351), so an id-only statement
// would not be exploitable through it. But GET /v1/auth/tokens returns every
// caller the UUIDs of their own sessions, and the per-session revoke endpoint
// that list exists to enable would take its id from the path - at which point
// an id-only DELETE is an IDOR that force-logs-out any user, admins included.
// See TestDeleteToken_IsScopedToTheOwningUser.
//
//	DELETE FROM api_tokens WHERE id = $1 AND user_id = $2
func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) error {
	_, err := q.db.Exec(ctx, deleteToken, arg.ID, arg.UserID)
	return err
}

const deleteTokensForUser = `-- name: DeleteTokensForUser :exec
DELETE FROM api_tokens WHERE user_id = $1
`

// DeleteTokensForUser
//
//	DELETE FROM api_tokens WHERE user_id = $1
func (q *Queries) DeleteTokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTokensForUser, userID)
	return err
}

const getTokenWithUser = `-- name: GetTokenWithUser :one
SELECT
    t.id          AS token_id,
    t.user_id     AS token_user_id,
    t.token_hash,
    t.created_at  AS token_created_at,
    t.expires_at,
    u.id          AS user_id,
    u.name        AS user_name,
    u.email       AS user_email,
    u.is_admin    AS user_is_admin
FROM api_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
  AND u.archived_at IS NULL
`

type GetTokenWithUserRow struct {
	TokenID        pgtype.UUID        `json:"token_id"`
	TokenUserID    pgtype.UUID        `json:"token_user_id"`
	TokenHash      string             `json:"token_hash"`
	TokenCreatedAt pgtype.Timestamptz `json:"token_created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	UserID         pgtype.UUID        `json:"user_id"`
	UserName       string             `json:"user_name"`
	UserEmail      string             `json:"user_email"`
	UserIsAdmin    bool               `json:"user_is_admin"`
}

// GetTokenWithUser
//
//	SELECT
//	    t.id          AS token_id,
//	    t.user_id     AS token_user_id,
//	    t.token_hash,
//	    t.created_at  AS token_created_at,
//	    t.expires_at,
//	    u.id          AS user_id,
//	    u.name        AS user_name,
//	    u.email       AS user_email,
//	    u.is_admin    AS user_is_admin
//	FROM api_tokens t
//	JOIN users u ON u.id = t.user_id
//	WHERE t.token_hash = $1
//	  AND u.archived_at IS NULL
func (q *Queries) GetTokenWithUser(ctx context.Context, tokenHash string) (GetTokenWithUserRow, error) {
	row := q.db.QueryRow(ctx, getTokenWithUser, tokenHash)
	var i GetTokenWithUserRow
	err := row.Scan(
		&i.TokenID,
		&i.TokenUserID,
		&i.TokenHash,
		&i.TokenCreatedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.UserName,
		&i.UserEmail,
		&i.UserIsAdmin,
	)
	return i, err
}

const listActiveTokensForUserPage = `-- name: ListActiveTokensForUserPage :many
SELECT id, created_at, expires_at
FROM api_tokens
WHERE user_id = $1
  AND (expires_at IS NULL OR expires_at > NOW())
  AND ($2::bool = FALSE
       OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5::int + 1
`

type ListActiveTokensForUserPageParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CursorSet bool               `json:"cursor_set"`
	CursorTs  pgtype.Timestamptz `json:"cursor_ts"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	PageLimit int32              `json:"page_limit"`
}

type ListActiveTokensForUserPageRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// One page of the caller's own API tokens, newest first.
//
// The projection is EXPLICIT and omits token_hash. That is the endpoint's
// security control: with the column absent from the SELECT, the generated row
// type has no field for it, so returning it is a compile error rather than a
// review miss. The handler has no reason to hold a hash at all - the
// current-session flag is a UUID comparison against the token id BearerAuth
// already resolved (internal/api/middleware.go:36-42), not a re-hash of the
// presented credential.
//
// user_id comes from the request context, never from the query string. There is
// no user_id parameter on the endpoint and there must never be one.
//
// The `expires_at IS NULL OR` arm is MANDATORY, not defensive noise. The column
// is nullable (000001_initial.up.sql:18) and a NULL means "never expires":
// BearerAuth rejects only on `Valid && Before(now)` (internal/api/middleware.go:32-35),
// so a NULL-expiry token authenticates forever. A bare `expires_at > NOW()`
// would hide exactly the most powerful credentials in the system from the one
// screen a user goes to in order to find them. Keep this predicate identical in
// all three statements here, including the count, or the pagination footer
// states a number the caller cannot page to. See
// TestListTokens_NeverExpiringTokenIsListed.
//
// Expired rows are excluded because they cannot authenticate, nothing reaps
// them (there is no janitor for api_tokens the way cmd/relay-server/main.go:253
// reaps agent_enrollments), and there is no per-row revoke endpoint, so listing
// them would render rows with no available action.
//
//	SELECT id, created_at, expires_at
//	FROM api_tokens
//	WHERE user_id = $1
//	  AND (expires_at IS NULL OR expires_at > NOW())
//	  AND ($2::bool = FALSE
//	       OR (created_at, id) < ($3::timestamptz, $4::uuid))
//	ORDER BY created_at DESC, id DESC
//	LIMIT $5::int + 1
func (q *Queries) ListActiveTokensForUserPage(ctx context.Context, arg ListActiveTokensForUserPageParams) ([]ListActiveTokensForUserPageRow, error) {
	rows, err := q.db.Query(ctx, listActiveTokensForUserPage,
		arg.UserID,
		arg.CursorSet,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTokensForUserPageRow
	for rows.Next() {
		var i ListActiveTokensForUserPageRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTokensForUserPageByCreatedAsc = `-- name: ListActiveTokensForUserPageByCreatedAsc :many
SELECT id, created_at, expires_at
FROM api_tokens
WHERE user_id = $1
  AND (expires_at IS NULL OR expires_at > NOW())
  AND ($2::bool = FALSE
       OR (created_at, id) > ($3::timestamptz, $4::uuid))
ORDER BY created_at ASC, id ASC
LIMIT $5::int + 1
`

type ListActiveTokensForUserPageByCreatedAscParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CursorSet bool               `json:"cursor_set"`
	CursorTs  pgtype.Timestamptz `json:"cursor_ts"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	PageLimit int32              `json:"page_limit"`
}

type ListActiveTokensForUserPageByCreatedAscRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// The ascending arm. parseSort strips a leading '-' before the allowlist check
// (internal/api/pagination.go:178-181), so both directions of created_at are
// reachable and each needs its own statement and dispatch arm.
//
// expires_at is deliberately NOT a sort key: the column is nullable, so it
// would need the NULLS LAST / NULLS FIRST index pair and the cursor-null
// handling that 000013_paginated_sort_indexes.up.sql:15-16 needed for
// workers.last_seen_at, for a list whose realistic length is single digits.
//
// Same expiry predicate as ListActiveTokensForUserPage; see the note there.
//
//	SELECT id, created_at, expires_at
//	FROM api_tokens
//	WHERE user_id = $1
//	  AND (expires_at IS NULL OR expires_at > NOW())
//	  AND ($2::bool = FALSE
//	       OR (created_at, id) > ($3::timestamptz, $4::uuid))
//	ORDER BY created_at ASC, id ASC
//	LIMIT $5::int + 1
func (q *Queries) ListActiveTokensForUserPageByCreatedAsc(ctx context.Context, arg ListActiveTokensForUserPageByCreatedAscParams) ([]ListActiveTokensForUserPageByCreatedAscRow, error) {
	rows, err := q.db.Query(ctx, listActiveTokensForUserPageByCreatedAsc,
		arg.UserID,
		arg.CursorSet,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTokensForUserPageByCreatedAscRow
	for rows.Next() {
		var i ListActiveTokensForUserPageByCreatedAscRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
