// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one
INSERT INTO api_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, created_at, expires_at
`

type CreateTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// CreateToken
//
//	INSERT INTO api_tokens (user_id, token_hash, expires_at)
//	VALUES ($1, $2, $3)
//	RETURNING id, user_id, token_hash, created_at, expires_at
func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTokenWithUser = `-- name: GetTokenWithUser :one
SELECT
    t.id          AS token_id,
    t.user_id     AS token_user_id,
    t.token_hash,
    t.created_at  AS token_created_at,
    t.expires_at,
    u.id          AS user_id,
    u.name        AS user_name,
    u.email       AS user_email,
    u.is_admin    AS user_is_admin
FROM api_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
`

type GetTokenWithUserRow struct {
	TokenID        pgtype.UUID        `json:"token_id"`
	TokenUserID    pgtype.UUID        `json:"token_user_id"`
	TokenHash      string             `json:"token_hash"`
	TokenCreatedAt pgtype.Timestamptz `json:"token_created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	UserID         pgtype.UUID        `json:"user_id"`
	UserName       string             `json:"user_name"`
	UserEmail      string             `json:"user_email"`
	UserIsAdmin    bool               `json:"user_is_admin"`
}

// GetTokenWithUser
//
//	SELECT
//	    t.id          AS token_id,
//	    t.user_id     AS token_user_id,
//	    t.token_hash,
//	    t.created_at  AS token_created_at,
//	    t.expires_at,
//	    u.id          AS user_id,
//	    u.name        AS user_name,
//	    u.email       AS user_email,
//	    u.is_admin    AS user_is_admin
//	FROM api_tokens t
//	JOIN users u ON u.id = t.user_id
//	WHERE t.token_hash = $1
func (q *Queries) GetTokenWithUser(ctx context.Context, tokenHash string) (GetTokenWithUserRow, error) {
	row := q.db.QueryRow(ctx, getTokenWithUser, tokenHash)
	var i GetTokenWithUserRow
	err := row.Scan(
		&i.TokenID,
		&i.TokenUserID,
		&i.TokenHash,
		&i.TokenCreatedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.UserName,
		&i.UserEmail,
		&i.UserIsAdmin,
	)
	return i, err
}
