// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminExists = `-- name: AdminExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE is_admin = TRUE
) AS "exists"
`

// AdminExists
//
//	SELECT EXISTS(
//	    SELECT 1 FROM users WHERE is_admin = TRUE
//	) AS "exists"
func (q *Queries) AdminExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, adminExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const archiveUser = `-- name: ArchiveUser :one
UPDATE users SET archived_at = NOW()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, email, name, is_admin, created_at, archived_at
`

type ArchiveUserRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	IsAdmin    bool               `json:"is_admin"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

// ArchiveUser
//
//	UPDATE users SET archived_at = NOW()
//	WHERE id = $1 AND archived_at IS NULL
//	RETURNING id, email, name, is_admin, created_at, archived_at
func (q *Queries) ArchiveUser(ctx context.Context, id pgtype.UUID) (ArchiveUserRow, error) {
	row := q.db.QueryRow(ctx, archiveUser, id)
	var i ArchiveUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT COUNT(*) FROM users
WHERE is_admin = TRUE AND archived_at IS NULL
`

// CountActiveAdmins
//
//	SELECT COUNT(*) FROM users
//	WHERE is_admin = TRUE AND archived_at IS NULL
func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE archived_at IS NULL
`

// CountUsers
//
//	SELECT COUNT(*) FROM users WHERE archived_at IS NULL
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersIncludingArchived = `-- name: CountUsersIncludingArchived :one
SELECT COUNT(*) FROM users
`

// CountUsersIncludingArchived
//
//	SELECT COUNT(*) FROM users
func (q *Queries) CountUsersIncludingArchived(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersIncludingArchived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (name, email, is_admin, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, is_admin, created_at, password_hash, archived_at
`

type CreateUserWithPasswordParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	IsAdmin      bool   `json:"is_admin"`
	PasswordHash string `json:"password_hash"`
}

// CreateUserWithPassword
//
//	INSERT INTO users (name, email, is_admin, password_hash)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, name, email, is_admin, created_at, password_hash, archived_at
func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithPassword,
		arg.Name,
		arg.Email,
		arg.IsAdmin,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.ArchivedAt,
	)
	return i, err
}

const deleteUserAPITokens = `-- name: DeleteUserAPITokens :execrows
DELETE FROM api_tokens WHERE user_id = $1
`

// DeleteUserAPITokens
//
//	DELETE FROM api_tokens WHERE user_id = $1
func (q *Queries) DeleteUserAPITokens(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserAPITokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, is_admin, created_at, password_hash, archived_at FROM users WHERE id = $1
`

// GetUser
//
//	SELECT id, name, email, is_admin, created_at, password_hash, archived_at FROM users WHERE id = $1
func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.ArchivedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, is_admin, created_at, password_hash, archived_at FROM users WHERE email = $1
`

// GetUserByEmail
//
//	SELECT id, name, email, is_admin, created_at, password_hash, archived_at FROM users WHERE email = $1
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.ArchivedAt,
	)
	return i, err
}

const getUserByEmailPublic = `-- name: GetUserByEmailPublic :one
SELECT id, email, name, is_admin, created_at, archived_at
FROM users WHERE email = $1
`

type GetUserByEmailPublicRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	IsAdmin    bool               `json:"is_admin"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

// GetUserByEmailPublic
//
//	SELECT id, email, name, is_admin, created_at, archived_at
//	FROM users WHERE email = $1
func (q *Queries) GetUserByEmailPublic(ctx context.Context, email string) (GetUserByEmailPublicRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailPublic, email)
	var i GetUserByEmailPublicRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listUsersIncludingArchivedPage = `-- name: ListUsersIncludingArchivedPage :many
SELECT id, email, name, is_admin, created_at, archived_at
FROM users
WHERE ($1::bool = FALSE
       OR (created_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4::int + 1
`

type ListUsersIncludingArchivedPageParams struct {
	CursorSet bool               `json:"cursor_set"`
	CursorTs  pgtype.Timestamptz `json:"cursor_ts"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	PageLimit int32              `json:"page_limit"`
}

type ListUsersIncludingArchivedPageRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	IsAdmin    bool               `json:"is_admin"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

// ListUsersIncludingArchivedPage
//
//	SELECT id, email, name, is_admin, created_at, archived_at
//	FROM users
//	WHERE ($1::bool = FALSE
//	       OR (created_at, id) < ($2::timestamptz, $3::uuid))
//	ORDER BY created_at DESC, id DESC
//	LIMIT $4::int + 1
func (q *Queries) ListUsersIncludingArchivedPage(ctx context.Context, arg ListUsersIncludingArchivedPageParams) ([]ListUsersIncludingArchivedPageRow, error) {
	rows, err := q.db.Query(ctx, listUsersIncludingArchivedPage,
		arg.CursorSet,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersIncludingArchivedPageRow
	for rows.Next() {
		var i ListUsersIncludingArchivedPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersIncludingArchivedPageByCreatedAsc = `-- name: ListUsersIncludingArchivedPageByCreatedAsc :many
SELECT id, email, name, is_admin, created_at, archived_at
FROM users
WHERE ($1::bool = FALSE
       OR (created_at, id) > ($2::timestamptz, $3::uuid))
ORDER BY created_at ASC, id ASC
LIMIT $4::int + 1
`

type ListUsersIncludingArchivedPageByCreatedAscParams struct {
	CursorSet bool               `json:"cursor_set"`
	CursorTs  pgtype.Timestamptz `json:"cursor_ts"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	PageLimit int32              `json:"page_limit"`
}

type ListUsersIncludingArchivedPageByCreatedAscRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	IsAdmin    bool               `json:"is_admin"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

// ListUsersIncludingArchivedPageByCreatedAsc
//
//	SELECT id, email, name, is_admin, created_at, archived_at
//	FROM users
//	WHERE ($1::bool = FALSE
//	       OR (created_at, id) > ($2::timestamptz, $3::uuid))
//	ORDER BY created_at ASC, id ASC
//	LIMIT $4::int + 1
func (q *Queries) ListUsersIncludingArchivedPageByCreatedAsc(ctx context.Context, arg ListUsersIncludingArchivedPageByCreatedAscParams) ([]ListUsersIncludingArchivedPageByCreatedAscRow, error) {
	rows, err := q.db.Query(ctx, listUsersIncludingArchivedPageByCreatedAsc,
		arg.CursorSet,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersIncludingArchivedPageByCreatedAscRow
	for rows.Next() {
		var i ListUsersIncludingArchivedPageByCreatedAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersIncludingArchivedPageByEmailAsc = `-- name: ListUsersIncludingArchivedPageByEmailAsc :many
SELECT id, email, name, is_admin, created_at, archived_at
FROM users
WHERE ($1::bool = FALSE
       OR (email, id) > ($2::text, $3::uuid))
ORDER BY email ASC, id ASC
LIMIT $4::int + 1
`

type ListUsersIncludingArchivedPageByEmailAscParams struct {
	CursorSet bool        `json:"cursor_set"`
	CursorV   string      `json:"cursor_v"`
	CursorID  pgtype.UUID `json:"cursor_id"`
	PageLimit int32       `json:"page_limit"`
}

type ListUsersIncludingArchivedPageByEmailAscRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	IsAdmin    bool               `json:"is_admin"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

// ListUsersIncludingArchivedPageByEmailAsc
//
//	SELECT id, email, name, is_admin, created_at, archived_at
//	FROM users
//	WHERE ($1::bool = FALSE
//	       OR (email, id) > ($2::text, $3::uuid))
//	ORDER BY email ASC, id ASC
//	LIMIT $4::int + 1
func (q *Queries) ListUsersIncludingArchivedPageByEmailAsc(ctx context.Context, arg ListUsersIncludingArchivedPageByEmailAscParams) ([]ListUsersIncludingArchivedPageByEmailAscRow, error) {
	rows, err := q.db.Query(ctx, listUsersIncludingArchivedPageByEmailAsc,
		arg.CursorSet,
		arg.CursorV,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersIncludingArchivedPageByEmailAscRow
	for rows.Next() {
		var i ListUsersIncludingArchivedPageByEmailAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersIncludingArchivedPageByEmailDesc = `-- name: ListUsersIncludingArchivedPageByEmailDesc :many
SELECT id, email, name, is_admin, created_at, archived_at
FROM users
WHERE ($1::bool = FALSE
       OR (email, id) < ($2::text, $3::uuid))
ORDER BY email DESC, id DESC
LIMIT $4::int + 1
`

type ListUsersIncludingArchivedPageByEmailDescParams struct {
	CursorSet bool        `json:"cursor_set"`
	CursorV   string      `json:"cursor_v"`
	CursorID  pgtype.UUID `json:"cursor_id"`
	PageLimit int32       `json:"page_limit"`
}

type ListUsersIncludingArchivedPageByEmailDescRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	IsAdmin    bool               `json:"is_admin"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

// ListUsersIncludingArchivedPageByEmailDesc
//
//	SELECT id, email, name, is_admin, created_at, archived_at
//	FROM users
//	WHERE ($1::bool = FALSE
//	       OR (email, id) < ($2::text, $3::uuid))
//	ORDER BY email DESC, id DESC
//	LIMIT $4::int + 1
func (q *Queries) ListUsersIncludingArchivedPageByEmailDesc(ctx context.Context, arg ListUsersIncludingArchivedPageByEmailDescParams) ([]ListUsersIncludingArchivedPageByEmailDescRow, error) {
	rows, err := q.db.Query(ctx, listUsersIncludingArchivedPageByEmailDesc,
		arg.CursorSet,
		arg.CursorV,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersIncludingArchivedPageByEmailDescRow
	for rows.Next() {
		var i ListUsersIncludingArchivedPageByEmailDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersIncludingArchivedPageByNameAsc = `-- name: ListUsersIncludingArchivedPageByNameAsc :many
SELECT id, email, name, is_admin, created_at, archived_at
FROM users
WHERE ($1::bool = FALSE
       OR (name, id) > ($2::text, $3::uuid))
ORDER BY name ASC, id ASC
LIMIT $4::int + 1
`

type ListUsersIncludingArchivedPageByNameAscParams struct {
	CursorSet bool        `json:"cursor_set"`
	CursorV   string      `json:"cursor_v"`
	CursorID  pgtype.UUID `json:"cursor_id"`
	PageLimit int32       `json:"page_limit"`
}

type ListUsersIncludingArchivedPageByNameAscRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	IsAdmin    bool               `json:"is_admin"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

// ListUsersIncludingArchivedPageByNameAsc
//
//	SELECT id, email, name, is_admin, created_at, archived_at
//	FROM users
//	WHERE ($1::bool = FALSE
//	       OR (name, id) > ($2::text, $3::uuid))
//	ORDER BY name ASC, id ASC
//	LIMIT $4::int + 1
func (q *Queries) ListUsersIncludingArchivedPageByNameAsc(ctx context.Context, arg ListUsersIncludingArchivedPageByNameAscParams) ([]ListUsersIncludingArchivedPageByNameAscRow, error) {
	rows, err := q.db.Query(ctx, listUsersIncludingArchivedPageByNameAsc,
		arg.CursorSet,
		arg.CursorV,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersIncludingArchivedPageByNameAscRow
	for rows.Next() {
		var i ListUsersIncludingArchivedPageByNameAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersIncludingArchivedPageByNameDesc = `-- name: ListUsersIncludingArchivedPageByNameDesc :many
SELECT id, email, name, is_admin, created_at, archived_at
FROM users
WHERE ($1::bool = FALSE
       OR (name, id) < ($2::text, $3::uuid))
ORDER BY name DESC, id DESC
LIMIT $4::int + 1
`

type ListUsersIncludingArchivedPageByNameDescParams struct {
	CursorSet bool        `json:"cursor_set"`
	CursorV   string      `json:"cursor_v"`
	CursorID  pgtype.UUID `json:"cursor_id"`
	PageLimit int32       `json:"page_limit"`
}

type ListUsersIncludingArchivedPageByNameDescRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	IsAdmin    bool               `json:"is_admin"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

// ListUsersIncludingArchivedPageByNameDesc
//
//	SELECT id, email, name, is_admin, created_at, archived_at
//	FROM users
//	WHERE ($1::bool = FALSE
//	       OR (name, id) < ($2::text, $3::uuid))
//	ORDER BY name DESC, id DESC
//	LIMIT $4::int + 1
func (q *Queries) ListUsersIncludingArchivedPageByNameDesc(ctx context.Context, arg ListUsersIncludingArchivedPageByNameDescParams) ([]ListUsersIncludingArchivedPageByNameDescRow, error) {
	rows, err := q.db.Query(ctx, listUsersIncludingArchivedPageByNameDesc,
		arg.CursorSet,
		arg.CursorV,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersIncludingArchivedPageByNameDescRow
	for rows.Next() {
		var i ListUsersIncludingArchivedPageByNameDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPage = `-- name: ListUsersPage :many
SELECT id, email, name, is_admin, created_at
FROM users
WHERE archived_at IS NULL
  AND ($1::bool = FALSE
       OR (created_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4::int + 1
`

type ListUsersPageParams struct {
	CursorSet bool               `json:"cursor_set"`
	CursorTs  pgtype.Timestamptz `json:"cursor_ts"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	PageLimit int32              `json:"page_limit"`
}

type ListUsersPageRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	IsAdmin   bool               `json:"is_admin"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ListUsersPage
//
//	SELECT id, email, name, is_admin, created_at
//	FROM users
//	WHERE archived_at IS NULL
//	  AND ($1::bool = FALSE
//	       OR (created_at, id) < ($2::timestamptz, $3::uuid))
//	ORDER BY created_at DESC, id DESC
//	LIMIT $4::int + 1
func (q *Queries) ListUsersPage(ctx context.Context, arg ListUsersPageParams) ([]ListUsersPageRow, error) {
	rows, err := q.db.Query(ctx, listUsersPage,
		arg.CursorSet,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersPageRow
	for rows.Next() {
		var i ListUsersPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPageByCreatedAsc = `-- name: ListUsersPageByCreatedAsc :many
SELECT id, email, name, is_admin, created_at
FROM users
WHERE archived_at IS NULL
  AND ($1::bool = FALSE
       OR (created_at, id) > ($2::timestamptz, $3::uuid))
ORDER BY created_at ASC, id ASC
LIMIT $4::int + 1
`

type ListUsersPageByCreatedAscParams struct {
	CursorSet bool               `json:"cursor_set"`
	CursorTs  pgtype.Timestamptz `json:"cursor_ts"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	PageLimit int32              `json:"page_limit"`
}

type ListUsersPageByCreatedAscRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	IsAdmin   bool               `json:"is_admin"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ListUsersPageByCreatedAsc
//
//	SELECT id, email, name, is_admin, created_at
//	FROM users
//	WHERE archived_at IS NULL
//	  AND ($1::bool = FALSE
//	       OR (created_at, id) > ($2::timestamptz, $3::uuid))
//	ORDER BY created_at ASC, id ASC
//	LIMIT $4::int + 1
func (q *Queries) ListUsersPageByCreatedAsc(ctx context.Context, arg ListUsersPageByCreatedAscParams) ([]ListUsersPageByCreatedAscRow, error) {
	rows, err := q.db.Query(ctx, listUsersPageByCreatedAsc,
		arg.CursorSet,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersPageByCreatedAscRow
	for rows.Next() {
		var i ListUsersPageByCreatedAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPageByEmailAsc = `-- name: ListUsersPageByEmailAsc :many
SELECT id, email, name, is_admin, created_at
FROM users
WHERE archived_at IS NULL
  AND ($1::bool = FALSE
       OR (email, id) > ($2::text, $3::uuid))
ORDER BY email ASC, id ASC
LIMIT $4::int + 1
`

type ListUsersPageByEmailAscParams struct {
	CursorSet bool        `json:"cursor_set"`
	CursorV   string      `json:"cursor_v"`
	CursorID  pgtype.UUID `json:"cursor_id"`
	PageLimit int32       `json:"page_limit"`
}

type ListUsersPageByEmailAscRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	IsAdmin   bool               `json:"is_admin"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ListUsersPageByEmailAsc
//
//	SELECT id, email, name, is_admin, created_at
//	FROM users
//	WHERE archived_at IS NULL
//	  AND ($1::bool = FALSE
//	       OR (email, id) > ($2::text, $3::uuid))
//	ORDER BY email ASC, id ASC
//	LIMIT $4::int + 1
func (q *Queries) ListUsersPageByEmailAsc(ctx context.Context, arg ListUsersPageByEmailAscParams) ([]ListUsersPageByEmailAscRow, error) {
	rows, err := q.db.Query(ctx, listUsersPageByEmailAsc,
		arg.CursorSet,
		arg.CursorV,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersPageByEmailAscRow
	for rows.Next() {
		var i ListUsersPageByEmailAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPageByEmailDesc = `-- name: ListUsersPageByEmailDesc :many
SELECT id, email, name, is_admin, created_at
FROM users
WHERE archived_at IS NULL
  AND ($1::bool = FALSE
       OR (email, id) < ($2::text, $3::uuid))
ORDER BY email DESC, id DESC
LIMIT $4::int + 1
`

type ListUsersPageByEmailDescParams struct {
	CursorSet bool        `json:"cursor_set"`
	CursorV   string      `json:"cursor_v"`
	CursorID  pgtype.UUID `json:"cursor_id"`
	PageLimit int32       `json:"page_limit"`
}

type ListUsersPageByEmailDescRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	IsAdmin   bool               `json:"is_admin"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ListUsersPageByEmailDesc
//
//	SELECT id, email, name, is_admin, created_at
//	FROM users
//	WHERE archived_at IS NULL
//	  AND ($1::bool = FALSE
//	       OR (email, id) < ($2::text, $3::uuid))
//	ORDER BY email DESC, id DESC
//	LIMIT $4::int + 1
func (q *Queries) ListUsersPageByEmailDesc(ctx context.Context, arg ListUsersPageByEmailDescParams) ([]ListUsersPageByEmailDescRow, error) {
	rows, err := q.db.Query(ctx, listUsersPageByEmailDesc,
		arg.CursorSet,
		arg.CursorV,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersPageByEmailDescRow
	for rows.Next() {
		var i ListUsersPageByEmailDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPageByNameAsc = `-- name: ListUsersPageByNameAsc :many
SELECT id, email, name, is_admin, created_at
FROM users
WHERE archived_at IS NULL
  AND ($1::bool = FALSE
       OR (name, id) > ($2::text, $3::uuid))
ORDER BY name ASC, id ASC
LIMIT $4::int + 1
`

type ListUsersPageByNameAscParams struct {
	CursorSet bool        `json:"cursor_set"`
	CursorV   string      `json:"cursor_v"`
	CursorID  pgtype.UUID `json:"cursor_id"`
	PageLimit int32       `json:"page_limit"`
}

type ListUsersPageByNameAscRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	IsAdmin   bool               `json:"is_admin"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ListUsersPageByNameAsc
//
//	SELECT id, email, name, is_admin, created_at
//	FROM users
//	WHERE archived_at IS NULL
//	  AND ($1::bool = FALSE
//	       OR (name, id) > ($2::text, $3::uuid))
//	ORDER BY name ASC, id ASC
//	LIMIT $4::int + 1
func (q *Queries) ListUsersPageByNameAsc(ctx context.Context, arg ListUsersPageByNameAscParams) ([]ListUsersPageByNameAscRow, error) {
	rows, err := q.db.Query(ctx, listUsersPageByNameAsc,
		arg.CursorSet,
		arg.CursorV,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersPageByNameAscRow
	for rows.Next() {
		var i ListUsersPageByNameAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPageByNameDesc = `-- name: ListUsersPageByNameDesc :many
SELECT id, email, name, is_admin, created_at
FROM users
WHERE archived_at IS NULL
  AND ($1::bool = FALSE
       OR (name, id) < ($2::text, $3::uuid))
ORDER BY name DESC, id DESC
LIMIT $4::int + 1
`

type ListUsersPageByNameDescParams struct {
	CursorSet bool        `json:"cursor_set"`
	CursorV   string      `json:"cursor_v"`
	CursorID  pgtype.UUID `json:"cursor_id"`
	PageLimit int32       `json:"page_limit"`
}

type ListUsersPageByNameDescRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	IsAdmin   bool               `json:"is_admin"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ListUsersPageByNameDesc
//
//	SELECT id, email, name, is_admin, created_at
//	FROM users
//	WHERE archived_at IS NULL
//	  AND ($1::bool = FALSE
//	       OR (name, id) < ($2::text, $3::uuid))
//	ORDER BY name DESC, id DESC
//	LIMIT $4::int + 1
func (q *Queries) ListUsersPageByNameDesc(ctx context.Context, arg ListUsersPageByNameDescParams) ([]ListUsersPageByNameDescRow, error) {
	rows, err := q.db.Query(ctx, listUsersPageByNameDesc,
		arg.CursorSet,
		arg.CursorV,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersPageByNameDescRow
	for rows.Next() {
		var i ListUsersPageByNameDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteUserToAdmin = `-- name: PromoteUserToAdmin :exec
UPDATE users SET is_admin = TRUE WHERE id = $1
`

// PromoteUserToAdmin
//
//	UPDATE users SET is_admin = TRUE WHERE id = $1
func (q *Queries) PromoteUserToAdmin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, promoteUserToAdmin, id)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetPasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

// SetPasswordHash
//
//	UPDATE users SET password_hash = $2 WHERE id = $1
func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const unarchiveUser = `-- name: UnarchiveUser :one
UPDATE users SET archived_at = NULL
WHERE id = $1 AND archived_at IS NOT NULL
RETURNING id, email, name, is_admin, created_at, archived_at
`

type UnarchiveUserRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	IsAdmin    bool               `json:"is_admin"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

// UnarchiveUser
//
//	UPDATE users SET archived_at = NULL
//	WHERE id = $1 AND archived_at IS NOT NULL
//	RETURNING id, email, name, is_admin, created_at, archived_at
func (q *Queries) UnarchiveUser(ctx context.Context, id pgtype.UUID) (UnarchiveUserRow, error) {
	row := q.db.QueryRow(ctx, unarchiveUser, id)
	var i UnarchiveUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users SET name = $2 WHERE id = $1
RETURNING id, email, name, is_admin, created_at, archived_at
`

type UpdateUserNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type UpdateUserNameRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	IsAdmin    bool               `json:"is_admin"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

// UpdateUserName
//
//	UPDATE users SET name = $2 WHERE id = $1
//	RETURNING id, email, name, is_admin, created_at, archived_at
func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (UpdateUserNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i UpdateUserNameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
