// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker_workspaces.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWorkerWorkspace = `-- name: DeleteWorkerWorkspace :exec
DELETE FROM worker_workspaces
WHERE worker_id = $1 AND source_type = $2 AND source_key = $3
`

type DeleteWorkerWorkspaceParams struct {
	WorkerID   pgtype.UUID `json:"worker_id"`
	SourceType string      `json:"source_type"`
	SourceKey  string      `json:"source_key"`
}

// DeleteWorkerWorkspace
//
//	DELETE FROM worker_workspaces
//	WHERE worker_id = $1 AND source_type = $2 AND source_key = $3
func (q *Queries) DeleteWorkerWorkspace(ctx context.Context, arg DeleteWorkerWorkspaceParams) error {
	_, err := q.db.Exec(ctx, deleteWorkerWorkspace, arg.WorkerID, arg.SourceType, arg.SourceKey)
	return err
}

const getWorkerWorkspace = `-- name: GetWorkerWorkspace :one
SELECT worker_id, source_type, source_key, short_id, baseline_hash, last_used_at FROM worker_workspaces
WHERE worker_id = $1 AND source_type = $2 AND source_key = $3
`

type GetWorkerWorkspaceParams struct {
	WorkerID   pgtype.UUID `json:"worker_id"`
	SourceType string      `json:"source_type"`
	SourceKey  string      `json:"source_key"`
}

// GetWorkerWorkspace
//
//	SELECT worker_id, source_type, source_key, short_id, baseline_hash, last_used_at FROM worker_workspaces
//	WHERE worker_id = $1 AND source_type = $2 AND source_key = $3
func (q *Queries) GetWorkerWorkspace(ctx context.Context, arg GetWorkerWorkspaceParams) (WorkerWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkerWorkspace, arg.WorkerID, arg.SourceType, arg.SourceKey)
	var i WorkerWorkspace
	err := row.Scan(
		&i.WorkerID,
		&i.SourceType,
		&i.SourceKey,
		&i.ShortID,
		&i.BaselineHash,
		&i.LastUsedAt,
	)
	return i, err
}

const listWarmWorkspacesForKeys = `-- name: ListWarmWorkspacesForKeys :many
SELECT worker_id, source_type, source_key, short_id, baseline_hash, last_used_at FROM worker_workspaces
WHERE source_type = $1 AND source_key = ANY($2::text[])
`

type ListWarmWorkspacesForKeysParams struct {
	SourceType string   `json:"source_type"`
	SourceKeys []string `json:"source_keys"`
}

// Used by dispatcher's warm-preference scoring. $1 is source_type, $2 is an
// array of source_keys observed in the current eligible-task batch.
//
//	SELECT worker_id, source_type, source_key, short_id, baseline_hash, last_used_at FROM worker_workspaces
//	WHERE source_type = $1 AND source_key = ANY($2::text[])
func (q *Queries) ListWarmWorkspacesForKeys(ctx context.Context, arg ListWarmWorkspacesForKeysParams) ([]WorkerWorkspace, error) {
	rows, err := q.db.Query(ctx, listWarmWorkspacesForKeys, arg.SourceType, arg.SourceKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkerWorkspace
	for rows.Next() {
		var i WorkerWorkspace
		if err := rows.Scan(
			&i.WorkerID,
			&i.SourceType,
			&i.SourceKey,
			&i.ShortID,
			&i.BaselineHash,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerWorkspaces = `-- name: ListWorkerWorkspaces :many
SELECT worker_id, source_type, source_key, short_id, baseline_hash, last_used_at FROM worker_workspaces
WHERE worker_id = $1
ORDER BY source_key
`

// ListWorkerWorkspaces
//
//	SELECT worker_id, source_type, source_key, short_id, baseline_hash, last_used_at FROM worker_workspaces
//	WHERE worker_id = $1
//	ORDER BY source_key
func (q *Queries) ListWorkerWorkspaces(ctx context.Context, workerID pgtype.UUID) ([]WorkerWorkspace, error) {
	rows, err := q.db.Query(ctx, listWorkerWorkspaces, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkerWorkspace
	for rows.Next() {
		var i WorkerWorkspace
		if err := rows.Scan(
			&i.WorkerID,
			&i.SourceType,
			&i.SourceKey,
			&i.ShortID,
			&i.BaselineHash,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceWorkerInventory = `-- name: ReplaceWorkerInventory :exec
DELETE FROM worker_workspaces WHERE worker_id = $1
`

// On agent reconnect: delete all existing rows for this worker and reinsert.
// Caller wraps in a transaction with subsequent UpsertWorkerWorkspace calls.
//
//	DELETE FROM worker_workspaces WHERE worker_id = $1
func (q *Queries) ReplaceWorkerInventory(ctx context.Context, workerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replaceWorkerInventory, workerID)
	return err
}

const upsertWorkerWorkspace = `-- name: UpsertWorkerWorkspace :exec
INSERT INTO worker_workspaces (worker_id, source_type, source_key, short_id, baseline_hash, last_used_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (worker_id, source_type, source_key) DO UPDATE
SET short_id = EXCLUDED.short_id,
    baseline_hash = EXCLUDED.baseline_hash,
    last_used_at = EXCLUDED.last_used_at
`

type UpsertWorkerWorkspaceParams struct {
	WorkerID     pgtype.UUID        `json:"worker_id"`
	SourceType   string             `json:"source_type"`
	SourceKey    string             `json:"source_key"`
	ShortID      string             `json:"short_id"`
	BaselineHash string             `json:"baseline_hash"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
}

// UpsertWorkerWorkspace
//
//	INSERT INTO worker_workspaces (worker_id, source_type, source_key, short_id, baseline_hash, last_used_at)
//	VALUES ($1, $2, $3, $4, $5, $6)
//	ON CONFLICT (worker_id, source_type, source_key) DO UPDATE
//	SET short_id = EXCLUDED.short_id,
//	    baseline_hash = EXCLUDED.baseline_hash,
//	    last_used_at = EXCLUDED.last_used_at
func (q *Queries) UpsertWorkerWorkspace(ctx context.Context, arg UpsertWorkerWorkspaceParams) error {
	_, err := q.db.Exec(ctx, upsertWorkerWorkspace,
		arg.WorkerID,
		arg.SourceType,
		arg.SourceKey,
		arg.ShortID,
		arg.BaselineHash,
		arg.LastUsedAt,
	)
	return err
}
