// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at
`

type CreateWorkerParams struct {
	Name     string `json:"name"`
	Hostname string `json:"hostname"`
	CpuCores int32  `json:"cpu_cores"`
	RamGb    int32  `json:"ram_gb"`
	GpuCount int32  `json:"gpu_count"`
	GpuModel string `json:"gpu_model"`
	Os       string `json:"os"`
}

// CreateWorker
//
//	INSERT INTO workers (name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at
func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, createWorker,
		arg.Name,
		arg.Hostname,
		arg.CpuCores,
		arg.RamGb,
		arg.GpuCount,
		arg.GpuModel,
		arg.Os,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CpuCores,
		&i.RamGb,
		&i.GpuCount,
		&i.GpuModel,
		&i.Os,
		&i.MaxSlots,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorker = `-- name: GetWorker :one
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at FROM workers WHERE id = $1
`

// GetWorker
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at FROM workers WHERE id = $1
func (q *Queries) GetWorker(ctx context.Context, id pgtype.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CpuCores,
		&i.RamGb,
		&i.GpuCount,
		&i.GpuModel,
		&i.Os,
		&i.MaxSlots,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkerByHostname = `-- name: GetWorkerByHostname :one
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at FROM workers WHERE hostname = $1
`

// GetWorkerByHostname
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at FROM workers WHERE hostname = $1
func (q *Queries) GetWorkerByHostname(ctx context.Context, hostname string) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByHostname, hostname)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CpuCores,
		&i.RamGb,
		&i.GpuCount,
		&i.GpuModel,
		&i.Os,
		&i.MaxSlots,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at FROM workers ORDER BY name
`

// ListWorkers
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at FROM workers ORDER BY name
func (q *Queries) ListWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.CpuCores,
			&i.RamGb,
			&i.GpuCount,
			&i.GpuModel,
			&i.Os,
			&i.MaxSlots,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorker = `-- name: UpdateWorker :one
UPDATE workers
SET name = $2, labels = $3, max_slots = $4
WHERE id = $1
RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at
`

type UpdateWorkerParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Labels   []byte      `json:"labels"`
	MaxSlots int32       `json:"max_slots"`
}

// UpdateWorker
//
//	UPDATE workers
//	SET name = $2, labels = $3, max_slots = $4
//	WHERE id = $1
//	RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at
func (q *Queries) UpdateWorker(ctx context.Context, arg UpdateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, updateWorker,
		arg.ID,
		arg.Name,
		arg.Labels,
		arg.MaxSlots,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CpuCores,
		&i.RamGb,
		&i.GpuCount,
		&i.GpuModel,
		&i.Os,
		&i.MaxSlots,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkerStatus = `-- name: UpdateWorkerStatus :one
UPDATE workers
SET status = $2, last_seen_at = $3
WHERE id = $1
RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at
`

type UpdateWorkerStatusParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

// UpdateWorkerStatus
//
//	UPDATE workers
//	SET status = $2, last_seen_at = $3
//	WHERE id = $1
//	RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at
func (q *Queries) UpdateWorkerStatus(ctx context.Context, arg UpdateWorkerStatusParams) (Worker, error) {
	row := q.db.QueryRow(ctx, updateWorkerStatus, arg.ID, arg.Status, arg.LastSeenAt)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CpuCores,
		&i.RamGb,
		&i.GpuCount,
		&i.GpuModel,
		&i.Os,
		&i.MaxSlots,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertWorkerByHostname = `-- name: UpsertWorkerByHostname :one
INSERT INTO workers (name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (hostname) DO UPDATE
    SET cpu_cores = EXCLUDED.cpu_cores,
        ram_gb    = EXCLUDED.ram_gb,
        gpu_count = EXCLUDED.gpu_count,
        gpu_model = EXCLUDED.gpu_model,
        os        = EXCLUDED.os
RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at
`

type UpsertWorkerByHostnameParams struct {
	Name     string `json:"name"`
	Hostname string `json:"hostname"`
	CpuCores int32  `json:"cpu_cores"`
	RamGb    int32  `json:"ram_gb"`
	GpuCount int32  `json:"gpu_count"`
	GpuModel string `json:"gpu_model"`
	Os       string `json:"os"`
}

// Insert a new worker or update hardware specs on reconnect.
// Admin-managed fields (name, labels, max_slots) are preserved on conflict.
//
//	INSERT INTO workers (name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	ON CONFLICT (hostname) DO UPDATE
//	    SET cpu_cores = EXCLUDED.cpu_cores,
//	        ram_gb    = EXCLUDED.ram_gb,
//	        gpu_count = EXCLUDED.gpu_count,
//	        gpu_model = EXCLUDED.gpu_model,
//	        os        = EXCLUDED.os
//	RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at
func (q *Queries) UpsertWorkerByHostname(ctx context.Context, arg UpsertWorkerByHostnameParams) (Worker, error) {
	row := q.db.QueryRow(ctx, upsertWorkerByHostname,
		arg.Name,
		arg.Hostname,
		arg.CpuCores,
		arg.RamGb,
		arg.GpuCount,
		arg.GpuModel,
		arg.Os,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CpuCores,
		&i.RamGb,
		&i.GpuCount,
		&i.GpuModel,
		&i.Os,
		&i.MaxSlots,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}
