// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearWorkerAgentToken = `-- name: ClearWorkerAgentToken :execrows
UPDATE workers
SET agent_token_hash = NULL, status = 'revoked'
WHERE id = $1
`

// ClearWorkerAgentToken
//
//	UPDATE workers
//	SET agent_token_hash = NULL, status = 'revoked'
//	WHERE id = $1
func (q *Queries) ClearWorkerAgentToken(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearWorkerAgentToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countWorkers = `-- name: CountWorkers :one
SELECT COUNT(*) FROM workers
`

// CountWorkers
//
//	SELECT COUNT(*) FROM workers
func (q *Queries) CountWorkers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at
`

type CreateWorkerParams struct {
	Name     string `json:"name"`
	Hostname string `json:"hostname"`
	CpuCores int32  `json:"cpu_cores"`
	RamGb    int32  `json:"ram_gb"`
	GpuCount int32  `json:"gpu_count"`
	GpuModel string `json:"gpu_model"`
	Os       string `json:"os"`
}

// CreateWorker
//
//	INSERT INTO workers (name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at
func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, createWorker,
		arg.Name,
		arg.Hostname,
		arg.CpuCores,
		arg.RamGb,
		arg.GpuCount,
		arg.GpuModel,
		arg.Os,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CpuCores,
		&i.RamGb,
		&i.GpuCount,
		&i.GpuModel,
		&i.Os,
		&i.MaxSlots,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.AgentTokenHash,
		&i.DisconnectedAt,
		&i.DisabledAt,
	)
	return i, err
}

const disableWorker = `-- name: DisableWorker :execrows
UPDATE workers SET disabled_at = NOW() WHERE id = $1 AND disabled_at IS NULL
`

// Marks a worker disabled. Idempotent: the disabled_at IS NULL guard means a
// second call affects zero rows and does not re-stamp the timestamp.
//
//	UPDATE workers SET disabled_at = NOW() WHERE id = $1 AND disabled_at IS NULL
func (q *Queries) DisableWorker(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, disableWorker, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enableWorker = `-- name: EnableWorker :execrows
UPDATE workers SET disabled_at = NULL WHERE id = $1 AND disabled_at IS NOT NULL
`

// Clears the disabled flag. Idempotent: affects zero rows if already enabled.
//
//	UPDATE workers SET disabled_at = NULL WHERE id = $1 AND disabled_at IS NOT NULL
func (q *Queries) EnableWorker(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, enableWorker, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorker = `-- name: GetWorker :one
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers WHERE id = $1
`

// GetWorker
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers WHERE id = $1
func (q *Queries) GetWorker(ctx context.Context, id pgtype.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CpuCores,
		&i.RamGb,
		&i.GpuCount,
		&i.GpuModel,
		&i.Os,
		&i.MaxSlots,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.AgentTokenHash,
		&i.DisconnectedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getWorkerByAgentTokenHash = `-- name: GetWorkerByAgentTokenHash :one
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
WHERE agent_token_hash = $1 AND status != 'revoked'
`

// GetWorkerByAgentTokenHash
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
//	WHERE agent_token_hash = $1 AND status != 'revoked'
func (q *Queries) GetWorkerByAgentTokenHash(ctx context.Context, agentTokenHash *string) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByAgentTokenHash, agentTokenHash)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CpuCores,
		&i.RamGb,
		&i.GpuCount,
		&i.GpuModel,
		&i.Os,
		&i.MaxSlots,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.AgentTokenHash,
		&i.DisconnectedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getWorkerByHostname = `-- name: GetWorkerByHostname :one
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers WHERE hostname = $1
`

// GetWorkerByHostname
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers WHERE hostname = $1
func (q *Queries) GetWorkerByHostname(ctx context.Context, hostname string) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByHostname, hostname)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CpuCores,
		&i.RamGb,
		&i.GpuCount,
		&i.GpuModel,
		&i.Os,
		&i.MaxSlots,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.AgentTokenHash,
		&i.DisconnectedAt,
		&i.DisabledAt,
	)
	return i, err
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers ORDER BY name
`

// ListWorkers
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers ORDER BY name
func (q *Queries) ListWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.CpuCores,
			&i.RamGb,
			&i.GpuCount,
			&i.GpuModel,
			&i.Os,
			&i.MaxSlots,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.AgentTokenHash,
			&i.DisconnectedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersByLiveness = `-- name: ListWorkersByLiveness :many
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers WHERE status IN ('online', 'stale')
`

// Workers eligible for staleness sweeping: those currently connected.
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers WHERE status IN ('online', 'stale')
func (q *Queries) ListWorkersByLiveness(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersByLiveness)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.CpuCores,
			&i.RamGb,
			&i.GpuCount,
			&i.GpuModel,
			&i.Os,
			&i.MaxSlots,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.AgentTokenHash,
			&i.DisconnectedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersPage = `-- name: ListWorkersPage :many
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
WHERE ($1::bool = FALSE
       OR (created_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4::int + 1
`

type ListWorkersPageParams struct {
	CursorSet bool               `json:"cursor_set"`
	CursorTs  pgtype.Timestamptz `json:"cursor_ts"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	PageLimit int32              `json:"page_limit"`
}

// ListWorkersPage
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
//	WHERE ($1::bool = FALSE
//	       OR (created_at, id) < ($2::timestamptz, $3::uuid))
//	ORDER BY created_at DESC, id DESC
//	LIMIT $4::int + 1
func (q *Queries) ListWorkersPage(ctx context.Context, arg ListWorkersPageParams) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersPage,
		arg.CursorSet,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.CpuCores,
			&i.RamGb,
			&i.GpuCount,
			&i.GpuModel,
			&i.Os,
			&i.MaxSlots,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.AgentTokenHash,
			&i.DisconnectedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersPageByCreatedAsc = `-- name: ListWorkersPageByCreatedAsc :many
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
WHERE NOT $1::bool OR (created_at, id) > ($2::timestamptz, $3::uuid)
ORDER BY created_at ASC, id ASC
LIMIT $4+ 1
`

type ListWorkersPageByCreatedAscParams struct {
	CursorSet bool               `json:"cursor_set"`
	CursorTs  pgtype.Timestamptz `json:"cursor_ts"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	PageLimit int32              `json:"+page_limit"`
}

// ListWorkersPageByCreatedAsc
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
//	WHERE NOT $1::bool OR (created_at, id) > ($2::timestamptz, $3::uuid)
//	ORDER BY created_at ASC, id ASC
//	LIMIT $4+ 1
func (q *Queries) ListWorkersPageByCreatedAsc(ctx context.Context, arg ListWorkersPageByCreatedAscParams) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersPageByCreatedAsc,
		arg.CursorSet,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.CpuCores,
			&i.RamGb,
			&i.GpuCount,
			&i.GpuModel,
			&i.Os,
			&i.MaxSlots,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.AgentTokenHash,
			&i.DisconnectedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersPageByLastSeenAsc = `-- name: ListWorkersPageByLastSeenAsc :many
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
WHERE NOT $1::bool
   OR (
       CASE WHEN $2::bool THEN
            (last_seen_at IS NULL AND id > $3::uuid)
         OR last_seen_at IS NOT NULL
       ELSE
            last_seen_at IS NOT NULL AND
            (last_seen_at, id) > ($4::timestamptz, $3::uuid)
       END
   )
ORDER BY last_seen_at ASC NULLS FIRST, id ASC
LIMIT $5+ 1
`

type ListWorkersPageByLastSeenAscParams struct {
	CursorSet    bool               `json:"cursor_set"`
	CursorIsNull bool               `json:"cursor_is_null"`
	CursorID     pgtype.UUID        `json:"cursor_id"`
	CursorTs     pgtype.Timestamptz `json:"cursor_ts"`
	PageLimit    int32              `json:"+page_limit"`
}

// ASC NULLS FIRST. Mirror image:
//
//   - cursor null: we're in the NULL head; qualify any null row with
//     id > cursor_id, OR any non-null row.
//
//   - cursor non-null: we're in the non-null tail; qualify non-null rows
//     with (last_seen_at, id) > (cursor_ts, cursor_id).
//
//     SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
//     WHERE NOT $1::bool
//     OR (
//     CASE WHEN $2::bool THEN
//     (last_seen_at IS NULL AND id > $3::uuid)
//     OR last_seen_at IS NOT NULL
//     ELSE
//     last_seen_at IS NOT NULL AND
//     (last_seen_at, id) > ($4::timestamptz, $3::uuid)
//     END
//     )
//     ORDER BY last_seen_at ASC NULLS FIRST, id ASC
//     LIMIT $5+ 1
func (q *Queries) ListWorkersPageByLastSeenAsc(ctx context.Context, arg ListWorkersPageByLastSeenAscParams) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersPageByLastSeenAsc,
		arg.CursorSet,
		arg.CursorIsNull,
		arg.CursorID,
		arg.CursorTs,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.CpuCores,
			&i.RamGb,
			&i.GpuCount,
			&i.GpuModel,
			&i.Os,
			&i.MaxSlots,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.AgentTokenHash,
			&i.DisconnectedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersPageByLastSeenDesc = `-- name: ListWorkersPageByLastSeenDesc :many
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
WHERE NOT $1::bool
   OR (
       CASE WHEN $2::bool THEN
            last_seen_at IS NULL AND id < $3::uuid
       ELSE
            (last_seen_at IS NOT NULL AND
             (last_seen_at, id) < ($4::timestamptz, $3::uuid))
         OR last_seen_at IS NULL
       END
   )
ORDER BY last_seen_at DESC NULLS LAST, id DESC
LIMIT $5+ 1
`

type ListWorkersPageByLastSeenDescParams struct {
	CursorSet    bool               `json:"cursor_set"`
	CursorIsNull bool               `json:"cursor_is_null"`
	CursorID     pgtype.UUID        `json:"cursor_id"`
	CursorTs     pgtype.Timestamptz `json:"cursor_ts"`
	PageLimit    int32              `json:"+page_limit"`
}

// DESC NULLS LAST. Cursor predicate splits on whether the cursor's
// last_seen value is null (@cursor_is_null::bool):
//
//   - cursor null: we're in the NULL tail; only rows that are also NULL
//     with id < cursor_id qualify.
//
//   - cursor non-null: we're in the non-null head; qualify any non-null
//     row with (last_seen_at, id) < (cursor_ts, cursor_id), OR any null
//     row (nulls come after in DESC NULLS LAST).
//
//     SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
//     WHERE NOT $1::bool
//     OR (
//     CASE WHEN $2::bool THEN
//     last_seen_at IS NULL AND id < $3::uuid
//     ELSE
//     (last_seen_at IS NOT NULL AND
//     (last_seen_at, id) < ($4::timestamptz, $3::uuid))
//     OR last_seen_at IS NULL
//     END
//     )
//     ORDER BY last_seen_at DESC NULLS LAST, id DESC
//     LIMIT $5+ 1
func (q *Queries) ListWorkersPageByLastSeenDesc(ctx context.Context, arg ListWorkersPageByLastSeenDescParams) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersPageByLastSeenDesc,
		arg.CursorSet,
		arg.CursorIsNull,
		arg.CursorID,
		arg.CursorTs,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.CpuCores,
			&i.RamGb,
			&i.GpuCount,
			&i.GpuModel,
			&i.Os,
			&i.MaxSlots,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.AgentTokenHash,
			&i.DisconnectedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersPageByNameAsc = `-- name: ListWorkersPageByNameAsc :many
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
WHERE NOT $1::bool OR (name, id) > ($2::text, $3::uuid)
ORDER BY name ASC, id ASC
LIMIT $4+ 1
`

type ListWorkersPageByNameAscParams struct {
	CursorSet bool        `json:"cursor_set"`
	CursorV   string      `json:"cursor_v"`
	CursorID  pgtype.UUID `json:"cursor_id"`
	PageLimit int32       `json:"+page_limit"`
}

// ListWorkersPageByNameAsc
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
//	WHERE NOT $1::bool OR (name, id) > ($2::text, $3::uuid)
//	ORDER BY name ASC, id ASC
//	LIMIT $4+ 1
func (q *Queries) ListWorkersPageByNameAsc(ctx context.Context, arg ListWorkersPageByNameAscParams) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersPageByNameAsc,
		arg.CursorSet,
		arg.CursorV,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.CpuCores,
			&i.RamGb,
			&i.GpuCount,
			&i.GpuModel,
			&i.Os,
			&i.MaxSlots,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.AgentTokenHash,
			&i.DisconnectedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersPageByNameDesc = `-- name: ListWorkersPageByNameDesc :many
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
WHERE NOT $1::bool OR (name, id) < ($2::text, $3::uuid)
ORDER BY name DESC, id DESC
LIMIT $4+ 1
`

type ListWorkersPageByNameDescParams struct {
	CursorSet bool        `json:"cursor_set"`
	CursorV   string      `json:"cursor_v"`
	CursorID  pgtype.UUID `json:"cursor_id"`
	PageLimit int32       `json:"+page_limit"`
}

// ListWorkersPageByNameDesc
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
//	WHERE NOT $1::bool OR (name, id) < ($2::text, $3::uuid)
//	ORDER BY name DESC, id DESC
//	LIMIT $4+ 1
func (q *Queries) ListWorkersPageByNameDesc(ctx context.Context, arg ListWorkersPageByNameDescParams) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersPageByNameDesc,
		arg.CursorSet,
		arg.CursorV,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.CpuCores,
			&i.RamGb,
			&i.GpuCount,
			&i.GpuModel,
			&i.Os,
			&i.MaxSlots,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.AgentTokenHash,
			&i.DisconnectedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersPageByStatusAsc = `-- name: ListWorkersPageByStatusAsc :many
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
WHERE NOT $1::bool OR (status, id) > ($2::text, $3::uuid)
ORDER BY status ASC, id ASC
LIMIT $4+ 1
`

type ListWorkersPageByStatusAscParams struct {
	CursorSet bool        `json:"cursor_set"`
	CursorV   string      `json:"cursor_v"`
	CursorID  pgtype.UUID `json:"cursor_id"`
	PageLimit int32       `json:"+page_limit"`
}

// ListWorkersPageByStatusAsc
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
//	WHERE NOT $1::bool OR (status, id) > ($2::text, $3::uuid)
//	ORDER BY status ASC, id ASC
//	LIMIT $4+ 1
func (q *Queries) ListWorkersPageByStatusAsc(ctx context.Context, arg ListWorkersPageByStatusAscParams) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersPageByStatusAsc,
		arg.CursorSet,
		arg.CursorV,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.CpuCores,
			&i.RamGb,
			&i.GpuCount,
			&i.GpuModel,
			&i.Os,
			&i.MaxSlots,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.AgentTokenHash,
			&i.DisconnectedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersPageByStatusDesc = `-- name: ListWorkersPageByStatusDesc :many
SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
WHERE NOT $1::bool OR (status, id) < ($2::text, $3::uuid)
ORDER BY status DESC, id DESC
LIMIT $4+ 1
`

type ListWorkersPageByStatusDescParams struct {
	CursorSet bool        `json:"cursor_set"`
	CursorV   string      `json:"cursor_v"`
	CursorID  pgtype.UUID `json:"cursor_id"`
	PageLimit int32       `json:"+page_limit"`
}

// ListWorkersPageByStatusDesc
//
//	SELECT id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at FROM workers
//	WHERE NOT $1::bool OR (status, id) < ($2::text, $3::uuid)
//	ORDER BY status DESC, id DESC
//	LIMIT $4+ 1
func (q *Queries) ListWorkersPageByStatusDesc(ctx context.Context, arg ListWorkersPageByStatusDescParams) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersPageByStatusDesc,
		arg.CursorSet,
		arg.CursorV,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.CpuCores,
			&i.RamGb,
			&i.GpuCount,
			&i.GpuModel,
			&i.Os,
			&i.MaxSlots,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.AgentTokenHash,
			&i.DisconnectedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkerAgentToken = `-- name: SetWorkerAgentToken :exec
UPDATE workers SET agent_token_hash = $2 WHERE id = $1
`

type SetWorkerAgentTokenParams struct {
	ID             pgtype.UUID `json:"id"`
	AgentTokenHash *string     `json:"agent_token_hash"`
}

// SetWorkerAgentToken
//
//	UPDATE workers SET agent_token_hash = $2 WHERE id = $1
func (q *Queries) SetWorkerAgentToken(ctx context.Context, arg SetWorkerAgentTokenParams) error {
	_, err := q.db.Exec(ctx, setWorkerAgentToken, arg.ID, arg.AgentTokenHash)
	return err
}

const setWorkerStatus = `-- name: SetWorkerStatus :exec
UPDATE workers SET status = $2 WHERE id = $1
`

type SetWorkerStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Updates only the status column, leaving last_seen_at and disconnected_at
// untouched. Used by the liveness sweeper for online<->stale transitions.
//
//	UPDATE workers SET status = $2 WHERE id = $1
func (q *Queries) SetWorkerStatus(ctx context.Context, arg SetWorkerStatusParams) error {
	_, err := q.db.Exec(ctx, setWorkerStatus, arg.ID, arg.Status)
	return err
}

const updateWorker = `-- name: UpdateWorker :one
UPDATE workers
SET name = $2, labels = $3, max_slots = $4
WHERE id = $1
RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at
`

type UpdateWorkerParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Labels   []byte      `json:"labels"`
	MaxSlots int32       `json:"max_slots"`
}

// UpdateWorker
//
//	UPDATE workers
//	SET name = $2, labels = $3, max_slots = $4
//	WHERE id = $1
//	RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at
func (q *Queries) UpdateWorker(ctx context.Context, arg UpdateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, updateWorker,
		arg.ID,
		arg.Name,
		arg.Labels,
		arg.MaxSlots,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CpuCores,
		&i.RamGb,
		&i.GpuCount,
		&i.GpuModel,
		&i.Os,
		&i.MaxSlots,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.AgentTokenHash,
		&i.DisconnectedAt,
		&i.DisabledAt,
	)
	return i, err
}

const updateWorkerStatus = `-- name: UpdateWorkerStatus :one
UPDATE workers
SET status = $2, last_seen_at = $3, disconnected_at = $4
WHERE id = $1
RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at
`

type UpdateWorkerStatusParams struct {
	ID             pgtype.UUID        `json:"id"`
	Status         string             `json:"status"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	DisconnectedAt pgtype.Timestamptz `json:"disconnected_at"`
}

// UpdateWorkerStatus
//
//	UPDATE workers
//	SET status = $2, last_seen_at = $3, disconnected_at = $4
//	WHERE id = $1
//	RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, agent_token_hash, disconnected_at, disabled_at
func (q *Queries) UpdateWorkerStatus(ctx context.Context, arg UpdateWorkerStatusParams) (Worker, error) {
	row := q.db.QueryRow(ctx, updateWorkerStatus,
		arg.ID,
		arg.Status,
		arg.LastSeenAt,
		arg.DisconnectedAt,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CpuCores,
		&i.RamGb,
		&i.GpuCount,
		&i.GpuModel,
		&i.Os,
		&i.MaxSlots,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.AgentTokenHash,
		&i.DisconnectedAt,
		&i.DisabledAt,
	)
	return i, err
}

const upsertWorkerByHostname = `-- name: UpsertWorkerByHostname :one
INSERT INTO workers (name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (hostname) DO UPDATE
    SET cpu_cores = EXCLUDED.cpu_cores,
        ram_gb    = EXCLUDED.ram_gb,
        gpu_count = EXCLUDED.gpu_count,
        gpu_model = EXCLUDED.gpu_model,
        os        = EXCLUDED.os
RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, disabled_at
`

type UpsertWorkerByHostnameParams struct {
	Name     string `json:"name"`
	Hostname string `json:"hostname"`
	CpuCores int32  `json:"cpu_cores"`
	RamGb    int32  `json:"ram_gb"`
	GpuCount int32  `json:"gpu_count"`
	GpuModel string `json:"gpu_model"`
	Os       string `json:"os"`
}

type UpsertWorkerByHostnameRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Hostname   string             `json:"hostname"`
	CpuCores   int32              `json:"cpu_cores"`
	RamGb      int32              `json:"ram_gb"`
	GpuCount   int32              `json:"gpu_count"`
	GpuModel   string             `json:"gpu_model"`
	Os         string             `json:"os"`
	MaxSlots   int32              `json:"max_slots"`
	Labels     []byte             `json:"labels"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
}

// Insert a new worker or update hardware specs on reconnect.
// Admin-managed fields (name, labels, max_slots) are preserved on conflict.
//
//	INSERT INTO workers (name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	ON CONFLICT (hostname) DO UPDATE
//	    SET cpu_cores = EXCLUDED.cpu_cores,
//	        ram_gb    = EXCLUDED.ram_gb,
//	        gpu_count = EXCLUDED.gpu_count,
//	        gpu_model = EXCLUDED.gpu_model,
//	        os        = EXCLUDED.os
//	RETURNING id, name, hostname, cpu_cores, ram_gb, gpu_count, gpu_model, os, max_slots, labels, status, last_seen_at, created_at, disabled_at
func (q *Queries) UpsertWorkerByHostname(ctx context.Context, arg UpsertWorkerByHostnameParams) (UpsertWorkerByHostnameRow, error) {
	row := q.db.QueryRow(ctx, upsertWorkerByHostname,
		arg.Name,
		arg.Hostname,
		arg.CpuCores,
		arg.RamGb,
		arg.GpuCount,
		arg.GpuModel,
		arg.Os,
	)
	var i UpsertWorkerByHostnameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CpuCores,
		&i.RamGb,
		&i.GpuCount,
		&i.GpuModel,
		&i.Os,
		&i.MaxSlots,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const workerStatusCounts = `-- name: WorkerStatusCounts :one
SELECT
    COUNT(*) FILTER (WHERE disabled_at IS NOT NULL)                    AS disabled,
    COUNT(*) FILTER (WHERE disabled_at IS NULL AND status = 'online')  AS online,
    COUNT(*) FILTER (WHERE disabled_at IS NULL AND status = 'stale')   AS stale,
    COUNT(*) FILTER (WHERE disabled_at IS NULL AND status = 'offline') AS offline
FROM workers
`

type WorkerStatusCountsRow struct {
	Disabled int64 `json:"disabled"`
	Online   int64 `json:"online"`
	Stale    int64 `json:"stale"`
	Offline  int64 `json:"offline"`
}

// Fleet-wide worker counts for the dashboard summary strip. "disabled" is an
// overlay (disabled_at IS NOT NULL) that wins over the internal status, mirroring
// toWorkerResponse. Revoked workers (not disabled) fall into no bucket and are
// excluded from the total computed by the caller.
//
//	SELECT
//	    COUNT(*) FILTER (WHERE disabled_at IS NOT NULL)                    AS disabled,
//	    COUNT(*) FILTER (WHERE disabled_at IS NULL AND status = 'online')  AS online,
//	    COUNT(*) FILTER (WHERE disabled_at IS NULL AND status = 'stale')   AS stale,
//	    COUNT(*) FILTER (WHERE disabled_at IS NULL AND status = 'offline') AS offline
//	FROM workers
func (q *Queries) WorkerStatusCounts(ctx context.Context) (WorkerStatusCountsRow, error) {
	row := q.db.QueryRow(ctx, workerStatusCounts)
	var i WorkerStatusCountsRow
	err := row.Scan(
		&i.Disabled,
		&i.Online,
		&i.Stale,
		&i.Offline,
	)
	return i, err
}
